### ISSUE TITLE
چند پیشنهاد

### ISSUE THREAD

**Issue by zoghal** [rastikerdar/samim-font#1]
درود بر شما
در ابتدا تبریک و تقدیر میکنم بابت سعی و تلاشی که دارید برای این فونت‌ می‌کشید. من به شخصه فونت وزیر رو از نظر اصول و قواعد طراحی حروف نپسندیدم، واقعیتش اون کار زیاد درستی نیست. اما این یکی کمی فرق داره.
 به خوبی برایم قابل لمس هست که دارید با سعی و تلاش و آزمون و خطا  به سمت طراحی صحیح و درست و اصولی حروف فارسی(یعنی هویت اصیل خط فارسی) سوق پیدا میکنید.  و جا داره تشکر ویژه‌ کنم. بگذریم.

پیشنهادات :
- کلمه رایگان را از ایندکس‌هاتون حذف کنید. بجایش خلاصه یا توضیح کوتاهی درمورد لایسنس آزاد بدید. به هرحال وقتی که میزارید ارزش مند هست و با این کلمه رایگان فقط ارزش کارتون و زحماتتون پایین می‌اید و انتظارات بالا می‌رود. در حال حاضردر جامعه فعلی فونت آنقدر بی ارزش هست که جامعه انتظار دارد هر فونتی رایگان باشد.
- پیشنهاد میکنم حتما کتاب فوق رو تهیه و مطالعه نمایید.خیلی کمکتون میکند.
  https://www.facebook.com/persianletters?fref=nf
  در حال حاضر دارید کمی منحرف میشید و باید از همین الان استایل فونت رو انتخاب کنید. استایل پایه فونت منولاین هست یعنی  ضخامت ها چه در عرض و طول باید یکسان باشد. و اگر قرار هست از منولاین خارج شوید باید روی تمامی حروف زاویه ها و استرس ها اعمال گردد.
  در بعضی حروف تناسبات صحیح نیست. این کتاب واقعا کمکتون میکنه.

یک خواهش :
لطفا در مورد خواسته‌های غیر استانداردی افراد سختگیری کنید مثل نمایش اعداد انگلیسی بجای فارسی. اینکار اشتباه هست و خیانت است تا خدمت. بذارید جامعه روش صحیح تولید محتوای فارسی را به واسطه همین فونت کمی آشنا و فرابگیره. راه را برایشان آسان نکنید.

چند نکته :
- برای راحت تر کار کردن با منحنی‌ها نوعشون رو cobic کنید. تا راحتر بتونید باهاشون بازی کنید.
- برای نمایش گلیف ها رو تغییر ندید مشکل رندر حل می شود این هم نمونه : http://i.share.pho.to/91f91647_o.png
- آخرین نسخه رو پوش کردید اطلاع بدید تا نسخه تصحیح شده را پوش کنم.

شاد و پیروز باشید

**Comment by rastikerdar** [comment]
سلام آقای سوزنچی.
- اولا از شما تشکر می کنم برای وقت و حوصله ای که به خرج دادید و امیدوارم به کمک همه دوستان این فونت و البته سایر فونت ها اصلاح شوند و مناسب برای استفاده همگان.
  به هر حال موضوع قلم بخش زیادیش به سلیقه بر می گردد. من خودم وزیر را  هم می پسندم کمااینکه وزیر بیش از صمیم مورد استقبال بوده. هر چند که برای متون طولانی صمیم رو بیشتر می پسندم با اینکه وزیر هم خوانا به نظر میرسه.
- منظور شما را از آزمون و خطا متوجه نمی شوم. این قلم ها آنچیزی بوده که در ذهنم جستجو می کردم و ظاهر فونت ها هم از روز نخست انتشار تغییری نداشته به جز یکی دو گلیف. اساسا تخصص من تولید فونت نیست که به دنبال مسائل پیرامونیش باشم.
- در مورد واژه رایگان همان روز نخستی که توصیه فرمودید به آن عمل نمودم و از صفحه ایندکس حذفش کردم.
- در مورد کتاب من در حوزه تخصصی خودم مشکلی با متون انگلیسی ندارم اما غیر از این برایم سخت و زمان بر است. البته نگاه من بیش از مسئله رسم الخط یا استایل و ... معطوف به خوانایی و هماهنگی و تا حدودی زیبایی بود. شما درست می فرمایید اما دو نکته وجود دارد. توی صمیم بنا بر این نبود که همه جا یک سایز باشد یا یکسری اصول سفت و سخت رعایت شود. صرفا آن چیزی که به چشم ها نرم و خوانا یا به طور کلی خوب بیاید.
  از طرفی چون تخصص من فونت نیست و این قلم از نگاه یک مخاطبی که به دنبال چنین شکلی بوده طراحی شده نتیجتا دور از انتظار نیست که بتوان اشکالات متعددی بر آن یافت.
- در مورد خواسته های غیر استاندارد این موضوع هم باید در نظر گرفت که بخش عمده ای از این مشکل یا قصور متوجه خود سیستم عامل و نرم افزار ها می باشد. طبیعتا همه این چیزها از جمله خود قلم ابزار هستند و در خدمت انسان و برای راحت تر و بهتر شدن کار انسان تولید شده اند. اگر بتوانیم به جای سخت گیری بیشتر، آموزش بیشتری بدهیم طبیعتا به تدریج این مسائل قابل رفع می باشد. من فکر می کنم در این مسئله اطلاع رسانی و فرهنگ سازی شما می تواند نقش موثری را ایفا نماید و همین که دائما این مسئله را به طور منطقی به عموم گوشزد نمایید ملکه ذهنشان می گردد

در مورد کوبیک که فرمودید حقیقتش من متوجه نشدم. خود فونت فورج مگر به صورت پیش فرض به چه - صورت است؟
- آخرین نسخه ممکن است کمی طول بکشد ولی اگر بفرمایید چه نوع اصلاحاتی مد نظرتان است و یا در پروژه و در قسمت ایشوها مشارکت نمایید فکر می کنم نتایج خوبی را به کمک همه دوستان می توان رقم زد.

سپاسگزارم
