### ISSUE TITLE
تغییر جزئی قطر قلم در ی متصل از راست

### ISSUE THREAD

**Issue by aziz** [rastikerdar/samim-font#10]
<img width="461" alt="screen shot 2015-11-14 at 12 31 42 pm" src="https://cloud.githubusercontent.com/assets/3202/11163347/cc70fdfa-8acb-11e5-8d44-c3d88c4abf50.png">

**Comment by rastikerdar** [comment]
فعلی:
![final yeh-old](https://cloud.githubusercontent.com/assets/3116038/11164798/48472e38-8b10-11e5-82ed-d9c08ed133ef.png)

جدید:
![final yeh-new](https://cloud.githubusercontent.com/assets/3116038/11164800/5717d58e-8b10-11e5-8712-4fdfde3f0934.png)

این تغییر زاویه برای رزولوشن های پایین بود جایی که موتور رندر، اون قسمت منحنی رو خالی یا کمرنگ می کرد در نتیجه ـي حالت افتادگی پیدا می کرد. من مجبور شدم برای اینکه اون ناحیه پر بشه بالاتر ببرم اما خب به محض بزرگنمایی این مشکل خودنمایی می کنه. اگر فکر می کنید جدیده بهتره که اعمال بشه.

**Comment by aziz** [comment]
به نظر من که جدید خیلی خیلی بهتره

**Comment by artlesshand** [comment]
:+1:

**Comment by artlesshand** [comment]
![ye-joint-01](https://cloud.githubusercontent.com/assets/763112/11165197/e60449e6-8b1d-11e5-8b14-322a726d586a.jpg)

**Comment by rastikerdar** [comment]
توی شاخه دولوپ 0.9.6 اعمال شد. متشکرم.

**Comment by artlesshand** [comment]
:+1:
