### ISSUE TITLE
لیگچر ﷼

### ISSUE THREAD

**Issue by aziz** [rastikerdar/samim-font#12]
<p dir='rtl' align='right'>یک فونت فارسی بدون لیگچر ﷼ مگه می‌شه؟‌ :smiley: </p>

**Comment by rastikerdar** [comment]
اولی بدون لیگچر و دومی با لیگچر
![rial](https://cloud.githubusercontent.com/assets/3116038/11177935/6c5e1dbe-8c5e-11e5-9a58-6b956c08d34d.png)

به نظرتون مناسبه؟

**Comment by artlesshand** [comment]
میتونی همون بالایی باشه ولی فشرده‌تر مثلا

**Comment by aziz** [comment]
مهمترین چیز به نظرم اینه که این یک علامته و باید فشرده باشه. امیدوار بودم کسی روی این سیمبول به صورت یک نماد بیشتر کار می‌کرد مثل دلار و یورو
نکته دوم اینه که همانطور که خودت دقت کردی این لیگچر از نظر قد و اندازه باید با اعداد کاملا هماهنگ باشه چون همیشه در کنار اعداد استفاده میشه. 
نکته سوم اینه که دیدم قلم ایران سنز لیگچر تومان هم داره که فکر نکنم کد استانداردی باشه ولی قطعا بسیار کاربردیه. 
نکته چهارم در مورد مستند‌سازی تمام این امکانات قلم است. به نظرم علاوه بر نمونه متن‌ها داشتن یک لیست یا جدول از این لیگچر‌ها و امکانات و قابلیت‌هایی که در آینده اضافه می‌کنی خیلی مفیده. شاید در زمینه برنچ گیت‌هاب پیجز من بتونم کمی کمک کنم. 

بی ربط: حالا چرا شش عدد ششصد رو عربی نوشتی :smile:

**Comment by rastikerdar** [comment]
خیلی خوبه این مواردی که فرمودید. عالیه. اما مشکل اینه که این موارد ممکنه زیاد طول بکشه چون همین کم کم ها خیلی زیاد میشه. اینجور کارها نیاز به مشارکت بالای شما دوستان داره. همین بحث مستندات و برنچ گیت هاب و ... نیاز به مدیریت و نگهداری داره که
حقیقتش بحث فونت کار اصلی من نیست برای همین خیلی بهتره تیمی بشه.

مشکل عدد ۶ از فایرفاکس من هست :)

**Comment by aziz** [comment]
من سعی می‌کنم تو اوقات آزادم کمی وقت بزارم.
سعی می‌کنم دیگران هم تشویق کنم کمک کنند

**Comment by rastikerdar** [comment]
هویجوری :D
![rial2](https://cloud.githubusercontent.com/assets/3116038/11189686/99b2a616-8ca6-11e5-843b-609c909e58a6.png)

**Comment by aziz** [comment]
باحاله. مطمئن نیستم تو سایزکوچیک هم خوب دیده می‌شه یا نه

**Comment by rastikerdar** [comment]
![rial3](https://cloud.githubusercontent.com/assets/3116038/11189785/37a40a54-8ca7-11e5-9231-58f7091eba79.png)

**Comment by rastikerdar** [comment]
اگه باز تر بشه بهتر میشه:

![rial4](https://cloud.githubusercontent.com/assets/3116038/11189964/6eb59ba6-8ca8-11e5-8ec3-c3444c317cb4.png)

**Comment by rastikerdar** [comment]
اگر فکر می کنید این خوبه همینو بزارم یا باز هم روش کار کنیم؟ قطعا اشکال بهتری هم میشه گذاشت. این سعی شده که جمع و جور و متفاوت و تا حدودی شکل و شمایل یک نویسه جداگانه یا مجزا رو داشته باشه.

؟

**Comment by artlesshand** [comment]
من با بالایی فعلا موافقم

**Comment by rastikerdar** [comment]
بالایی یعنی اولین تصویر از بالا؟

**Comment by artlesshand** [comment]
ریالی که دو نقطش رفته زیرش

**Comment by rastikerdar** [comment]
اونی که رفته زیرش منطقی تره و اونی که کنارشه جمع و جورتره. حالا هر جور صلاح می دونید.

**Comment by artlesshand** [comment]
چون لیگچر هست، من فکر میکنم نیازی به متعارف بودن نباشه،‌ و میشه با تایپوگرافی تغییرات داد روش. در نهایت چیزی مثل دالر ساین داریم معادلش

**Comment by rastikerdar** [comment]
این چطوره؟
![rial5](https://cloud.githubusercontent.com/assets/3116038/11425085/73734258-9467-11e5-956f-ce7d32b81ec9.png)

**Comment by artlesshand** [comment]
من دوسش ندارم

**Comment by rastikerdar** [comment]
اضافه شد اما تقریبا بدون تغییر تا اینکه یه روزی یه شکل استاندارد براش در بیارن.

با تشکر برای این ایشو و مباحثه.
