### ISSUE TITLE
طراحی فارسی شده گلیف‌هایی که از دژاوو به ارث رسیده

### ISSUE THREAD

**Issue by aziz** [rastikerdar/samim-font#13]
`؛  :  .  ؟ ! ٪`

این شش تا به نظرم مهم اومد و بیشترین کاربرد رو دارند.
<img width="530" alt="screen shot 2015-11-14 at 6 37 11 pm" src="https://cloud.githubusercontent.com/assets/3202/11164911/dec80f56-8afe-11e5-95fa-5771101430dc.png">

**Comment by aziz** [comment]
به اضافه اینها که در حالت بولد خیلی بد دیده میشه.

‍‍‍`«»`

**Comment by rastikerdar** [comment]
به نظرتون بهتر شده?

![marks](https://cloud.githubusercontent.com/assets/3116038/11169032/d84681e8-8bbd-11e5-9a10-307751f11025.png)

**Comment by aziz** [comment]
برای علامت تعجب تغییر قطر قلم در نزدیکی بیس‌لاین نباید شبیه الف باشه؟ 
نقطه ویرگول کمی نامتناسب شده. شاید باید ویرگول هم از همین شکل کلی نقطه‌ها پیروی کنه.

**Comment by rastikerdar** [comment]
علامت تعجب دو جهته است هم برای فارسی هست هم انگلیسی. یکدستش کردم. نقطه ویرگول هم متناسب شد. اگه خوبه اعمال بشه؟
![semi colon](https://cloud.githubusercontent.com/assets/3116038/11171419/3385bef6-8c05-11e5-8b0f-d4b119943dfd.png)
![exclam](https://cloud.githubusercontent.com/assets/3116038/11171420/3876f722-8c05-11e5-8fed-f413c5a3593c.png)

**Comment by aziz** [comment]
:+1:

**Comment by aziz** [comment]
این گیومه‌های رو هم دریاب صابرجان
«»

**Comment by rastikerdar** [comment]
به نظرت چه کارشون کنیم؟ مغزم خالی شده :P

**Comment by aziz** [comment]
به نظرت این چطوره؟
<img width="279" alt="screen shot 2015-11-15 at 11 58 19 pm" src="https://cloud.githubusercontent.com/assets/3202/11171614/d08f5542-8bf4-11e5-90e5-43de4618af27.png">

**Comment by rastikerdar** [comment]
یکم زیادی گرد نیست؟ شبیه پرانیز شده

**Comment by aziz** [comment]
شاید زیادی بزرگه. ولی کلا گرد بیشتر به این قلم میاد

**Comment by rastikerdar** [comment]
هممم آره فکر می کنم کوچکتر بشه خوب میشه

**Comment by rastikerdar** [comment]
این چطوره؟
![guillemot](https://cloud.githubusercontent.com/assets/3116038/11177176/db0f99dc-8c58-11e5-8c6c-59a0d5ab9092.png)

پرانتزها رو کوچک کردم

**Comment by artlesshand** [comment]
میشه داخل متن هم دید؟ یه پاراگراف که این وسطش باشه

**Comment by aziz** [comment]
به تنهایی خوبه ولی همونطور که فرزان گفت باید تو متن دیده بشه

**Comment by rastikerdar** [comment]
اگه یه صفحه تست داشته باشیم بشه چند تا حالت پر کاربرد رو رویش بررسی کنیم خیلی خوبه. فکر می کنم بد نیست یه ایشو برایش باز کنیم به گفت و گو و جمع بندی بپردازیم

**Comment by aziz** [comment]
این گیو‌مه‌های جدید رو من گلیف‌شون رو می‌بینم ولی وقتی تایپ می‌کنم کماکان همون «گلیف قدیمی دژاوو» تایپ میشه

**Comment by aziz** [comment]
عدم تراز درست ! و ؟ از نظر نقطه و خط بیس لاین
<img width="157" alt="screen shot 2015-11-18 at 10 17 43 pm" src="https://cloud.githubusercontent.com/assets/3202/11254660/53f963d8-8e42-11e5-8a72-f97a87b0d0bc.png">

**Comment by rastikerdar** [comment]
البته گیومه جدید رو تو ورژن جدید گذاشتم برای تست تا نظرتون رو بگید. فکر می کنم فضای خالی ما بین گیومه ها و واژه بیش از حده. 

در مورد تراز ؟ و ! هم کاملا حق با شماست. من بی دقتی کردم.

**Comment by rastikerdar** [comment]
هم ترازی اصلاح شد.

با تشکر.
