### ISSUE TITLE
بهینه شدن شکل ی و تناسب با باقی گلیف‌ها

### ISSUE THREAD

**Issue by artlesshand** [rastikerdar/samim-font#14]
به نظر من، انحنای آغازین شکل «ی» اگر یکم بازتر شه و بالاتر بیاد میتونه بهتر باشه، تقریبا مثل نمونه‌ی زیر:

![ye-character-2](https://cloud.githubusercontent.com/assets/763112/11165086/4b872ed6-8b1a-11e5-8b53-f2dd8ba00374.JPG)

**Comment by aziz** [comment]
:+1: دقیقا همینو می‌خواستم بگم

**Comment by rastikerdar** [comment]
البته ی در حالت معمولی به نظرتون خوب نیست؟
![yeh-regular](https://cloud.githubusercontent.com/assets/3116038/11165488/12e3d8ca-8b26-11e5-91df-001b5dfa6557.png)

چون به نظر میاد توی ضخیم جمع شده.

**Comment by aziz** [comment]
به نظرم سر ی به سمت بالا باشه و دهنه‌اش کمی بازتر بشه بهتره

**Comment by artlesshand** [comment]
موافقم

**Comment by rastikerdar** [comment]
این چطوره به نظر شما؟
![isolated yeh](https://cloud.githubusercontent.com/assets/3116038/11169558/dbca1c90-8bd0-11e5-9748-0dc60a952acc.png)

**Comment by aziz** [comment]
بهتر شده ولی تغییر قطر قلم در قوس ی کمی به چشم می‌زند

**Comment by rastikerdar** [comment]
بالا یا وسط؟

**Comment by aziz** [comment]
![download](https://cloud.githubusercontent.com/assets/3202/11169655/a9875fee-8bbd-11e5-8825-1a1d71a55f9d.png)

**Comment by artlesshand** [comment]
به نظرم من جا داره یکم متناسب تر شه ضخامت شروعش

**Comment by rastikerdar** [comment]
دیدگاه شما بیشتر به یک اندازه شدن همه ضخامت ها نزدیکه اما خب مثلا در دروید عربیک نسخ اندازه ها در بسیاری گلیف ها کم و زیاد می شود. به نوعی برای ایجاد توازن هست. اما خب شاید هم من اشتباه می کنم. در واقع طراحی همه گلیف بعد از الف شروع شد.

![yeh-design](https://cloud.githubusercontent.com/assets/3116038/11170784/fe537568-8bf3-11e5-88ed-505c93c59e71.png)

شما کدام یکی را می پسندین؟

**Comment by artlesshand** [comment]
نه من نمیخوام مونولاینش کنم، پایینی رو ترجیح میدم. ولی ضخامت به شکل منطقی تغییر نکرده توی تیکه‌ی قبل از پیچش

**Comment by rastikerdar** [comment]
منظورتون او خط وسطه یا شروع وسط یا همون ابتدای شروع از راست توی قوس پایینه؟

**Comment by artlesshand** [comment]
یه چیزی شبیه این مثلا

![y-curves-1](https://cloud.githubusercontent.com/assets/763112/11171034/584290e4-8bfa-11e5-9111-3c14c06a51a5.jpg)

منظورم این تیکست
![y-curves-2](https://cloud.githubusercontent.com/assets/763112/11171037/90e805a0-8bfa-11e5-879f-5a43e8a885f5.jpg)

**Comment by rastikerdar** [comment]
دومی به نظرم خیلی خوشگل شده :P
نسخه برنچ دولوپ ایجاد می کنم بهتون اطلاع میدم اگر برایتان امکان داره این ی رو بزارید توی اون پوش کنید.
بعد از نهایی شدن ادغام کنیم با اصلی.
ساختار پروژه از حالت فعلی باید در بیاد و به صورت ریلیزی بشه. عزیزان آقایان
Ebrahim Byagowi
و 
Behdad Abedi 
هم فرمودند که این تغییر ساختار لازمه انجام بشه اما فرصت نمی کردم و حتی فراموش کردم.

**Comment by artlesshand** [comment]
:)) مرسی 
اگر یه شیوه‌ی خوب و مکتوب برای کانتریبیوت ارایه بشه هم عالیه
که مثلا گلیف‌ها به شکلی طراحی شه، فرمت و غیره

**Comment by rastikerdar** [comment]
البته آقای مهدی پیشگوی عزیز هم به صورت ایمیل به این نازک شدن از میانه به ویژه در ـی متصل داشتند که من به مشکل ترافیک خطوط در اون ناحیه کوچک و تا حدودی بد ریخت شدن در رزولوشن های پایین اشاره کردم.
@tux-world

**Comment by rastikerdar** [comment]
خب ساختار پروژه تغییر کرد. اغلب نظراتی که بر روی آن‌ها توی ایشو ها توافق شد اعمال گردید. الان به صورت انتشاری یا همون ریلیزی درآمد. شما اگر فورک کنید و توی شاخه دولوپ شروع کنیم به تغییرات به راحتی میتونیم همه رو ادغام کنیم و در نهایت بریزیم توی مستر و فایل های نهایی و باینری رو منتشر کنیم.
قبل از ادغام تغییرات هم به راحتی اینجا مشورت می کنیم.
البته اگر روش بهتری مد نظرتان است حتما بفرمایید.

یه تشکر ویژه از @ebraminio
ایشان به صورت ایمیل خیلی خوب و با حوصله در مورد ساختار پروژه توضیح دادند.

همچنین تشکر از اشاره @behdad222 به این موضوع در ایمیلشان

**Comment by artlesshand** [comment]
بسیار عالی

**Comment by pishguy** [comment]
سلام . من هم پایینی رو میپسندم 
@rastikerdar

**Comment by rastikerdar** [comment]
قدیم:
![screenshot from 2015-12-23 00-18-03](https://cloud.githubusercontent.com/assets/3116038/11965585/bb6b7b04-a90a-11e5-8d1e-a0b65820e340.png)

جدید:
![screenshot from 2015-12-23 00-17-54](https://cloud.githubusercontent.com/assets/3116038/11965586/bd867e3e-a90a-11e5-932b-2b43caa85662.png)

**Comment by rastikerdar** [comment]
قدیم:
![screenshot from 2015-12-23 00-57-02](https://cloud.githubusercontent.com/assets/3116038/11966314/521d7f16-a910-11e5-9411-b1aa7204962a.png)

جدید:
![screenshot from 2015-12-23 00-57-09](https://cloud.githubusercontent.com/assets/3116038/11966324/613a4db2-a910-11e5-9884-7e01c2e2c665.png)

@artlesshand  @aziz

**Comment by zoghal** [comment]
خوب شد. . اما تو کنترل زخمات ها تعادلی وجود نداره. تو ی دقت کنید.

**Comment by rastikerdar** [comment]
@zoghal کاملا حق با شماست
بی دقتی کردم. حتما اصلاح می کنم.

**Comment by rastikerdar** [comment]
اصلاح شد.
با تشکر از فرزان و صالح و عزیز
