### ISSUE TITLE
شکستگی در اتصال کاف و گاف از راست

### ISSUE THREAD

**Issue by artlesshand** [rastikerdar/samim-font#15]
میتونه این شکستگی نرم‌تر بشه

![kaf-gaf-joint](https://cloud.githubusercontent.com/assets/763112/11165166/ddbbe7e0-8b1c-11e5-8397-b8408c5c93f5.jpg)

**Comment by rastikerdar** [comment]
به این شکل منظورتونه؟
![connected-kaf](https://cloud.githubusercontent.com/assets/3116038/11169064/fef598cc-8bbf-11e5-970d-b1804a14f43f.png)

**Comment by rastikerdar** [comment]
توی شاخه دولوپ 0.9.6 اعمال شد. متشکرم.

**Comment by artlesshand** [comment]
:+1:
