### ISSUE TITLE
کرنینگ لا و رزژ

### ISSUE THREAD

**Issue by artlesshand** [rastikerdar/samim-font#16]
میتونه کرنینگ لا با پیشروی که به چپ داره بهتر کنترل شه

![jh-kerning](https://cloud.githubusercontent.com/assets/763112/11165381/39b463ba-8b22-11e5-846d-d1f6df5378fa.jpg)

**Comment by rastikerdar** [comment]
در نسخه بولد که این فاصله ها نیاز به اصلاحاتی دارند. به دلیل اینکه بعد از ضخیم شدن اندازه ها دست نخورد به جوز سمت راست حروف جدا و ابتدا.
حروف وسط و انتها هم کلا دست نخوردند. البته دلیلش عدم کشیدگی و تا حدودی همخوانی با سایز معمولی بود اما کلا احتمالا جای کار زیادی دارد.

**Comment by artlesshand** [comment]
بسیار عالی

**Comment by aziz** [comment]
کلا رزژ مشگل کرنینگ دارند چه در بولد و چه در معمولی
به فاصله ز و م دقت کنید و اون رو با فاصله و و ن انتها مقایسه کنید
<img width="64" alt="screen shot 2015-11-15 at 7 00 31 pm" src="https://cloud.githubusercontent.com/assets/3202/11170121/a0f31734-8bcb-11e5-9724-f5acb30f577e.png">

**Comment by rastikerdar** [comment]
درست می فرمایید. البته یه توضیح کوتاه بدم که در دفعه نخست چیزی مثل آزمون پایینی در تصویر انجام شد و ز به زیر میم رفت اما توی جمله وقتی این زیر رفتن ها ر ز زیاد شد دیدم داره شلوغ میکنه و گفتم اگر چه فاصله زیاد کمی غیر عادی به نظر برسه اما از بار شلوغی کم می کنه. در تاهوما و دروید عربیک نسخ و میترا هم به همین صورت است و فاصله رو کم نکردند. ولی خب شاید پایینی بهتر باشه. نظر شما چیست؟

![kerning](https://cloud.githubusercontent.com/assets/3116038/11170846/c77504e2-8bf5-11e5-8246-b191aa27c607.png)

البته کرنینگ در خیلی فونت ها انجام نشده

**Comment by aziz** [comment]
به نظرم دومی صحیحتر و بهتر است. فاصله ز و م در اولی خیلی بیشتر از باقی فواصل است و به ظاهر کلمه صدمه زده

**Comment by artlesshand** [comment]
من با پایینی موافقم

**Comment by rastikerdar** [comment]
درست می فرمایید. البته به این هم اشاره کنم این فاصله به دلیل وجود فضای خالی بین ابتدا و انتهای ز است در صورتی که مثلا در واژه زیر این فضا ناگزیر به نظر میاد و حرف واو نمی تونه اونو پر کنه.

![kerning2](https://cloud.githubusercontent.com/assets/3116038/11178780/3e9db906-8c64-11e5-9a36-ae51542be1fa.png)

**Comment by artlesshand** [comment]
درسته، البته جا داره یه ذره واو بره عقب‌تر

**Comment by artlesshand** [comment]
درسته، البته جا داره یه ذره واو بره عقب‌تر

**Comment by rastikerdar** [comment]
واو توی رزولوشن پایین عقب تر بعضا می چسبم.
.کرنینگ ر ز ژ واقعا پر دردسره و پر زحمت
یه سری رو بهبود دادم
![kerning4](https://cloud.githubusercontent.com/assets/3116038/11207462/93d59436-8d2a-11e5-985d-ea12d63cc3ea.png)

**Comment by artlesshand** [comment]
بهتر شده
نقطه‌های ژ میتونه بیاد راست‌تر به نظرم، نه؟

**Comment by rastikerdar** [comment]
درسته. به ویژه در حالت ضخیم.

**Comment by artlesshand** [comment]
:+1:

**Comment by aziz** [comment]
این دو مثال زیر هم مشکل کرنینگ دارند. بین دو را در بررسی و بین را و واو در ورود
<img width="366" alt="screen shot 2015-11-28 at 11 17 57 am" src="https://cloud.githubusercontent.com/assets/3202/11451303/c01a8ad4-95c1-11e5-9c56-3c7cfcb8f55d.png">

**Comment by rastikerdar** [comment]
کرنینگ ر با حروف ر و اصلاح شد.
نقاط ژ هم اصلاح گردید.

اگر باز هم مشکلی بود ایشو رو باز بفرمایید.

با تشکر
