### ISSUE TITLE
بهینه شدن کلاه الف در وزن تیره

### ISSUE THREAD

**Issue by artlesshand** [rastikerdar/samim-font#17]
گلیف «آ» در هر دو وزن یک کلاه همشکل دارن. شاید اگر نسخه‌ی بولد کمی حجمش بیشتر شه، بهتر باشه:

![alef-bold](https://cloud.githubusercontent.com/assets/763112/11165401/07838e38-8b23-11e5-81a2-e1f16005ac98.jpg)

**Comment by rastikerdar** [comment]
انحنای ابتداییش هم یه کم مشکل داره.
برای این مد تغییر سایز انجام نشد به ویژه اعراب. توی سایت های مختلف که تست می کردم مخصوصا جملات پر اعراب عربی می دیدم پررنگ تر میشه خیلی ناجور و شلوغ و درهم میشه. البته در سایزهای کوچک. اما برای این مد به نظر حق با شماست. البته این نظر شخصی بود

**Comment by artlesshand** [comment]
آره فقط با تغییر مد موافقم، ممنون به هر حال

**Comment by aziz** [comment]
ی همزه دار هم همین مشکل را دارد
<img width="90" alt="screen shot 2015-11-15 at 6 21 03 pm" src="https://cloud.githubusercontent.com/assets/3202/11169936/bd117a2e-8bc5-11e5-8dfa-4f5e4f9a98dd.png">

**Comment by aziz** [comment]
سرکش گاف هم فکر کنم همین مشکل را در حالت بولد دارد. اگر علاقه‌ای به افزایش قطر نداری حداقل فاصله‌اش را با خود سرکش تنظیم کن چون تو مانیتورهای قدیمی خیلی بد دیده می‌شه.
<img width="76" alt="screen shot 2015-11-15 at 6 29 37 pm" src="https://cloud.githubusercontent.com/assets/3202/11169976/0b0373f8-8bc7-11e5-8218-afd557cedd9e.png">

**Comment by artlesshand** [comment]
:+1:

**Comment by rastikerdar** [comment]
توی شاخه دولوپ 0.9.6 اعمال شد. متشکرم.
البته اگر باز هم نیاز به اصلاح داشت باز بفرمایید.
