### ISSUE TITLE
اصلاح محل قرار گیری نقاط در زیر و بالای حروف

### ISSUE THREAD

**Issue by aziz** [rastikerdar/samim-font#18]
![](https://cloud.githubusercontent.com/assets/3116038/11164711/1f3b4c52-8b0d-11e5-8462-9897597ee0ad.png)
#6 را ببینید

**Comment by rastikerdar** [comment]
قدیم:
![screenshot from 2015-12-22 23-58-57](https://cloud.githubusercontent.com/assets/3116038/11965505/2ec8a2d0-a90a-11e5-9931-efc7f8a9ad26.png)

جدید:
![screenshot from 2015-12-22 23-58-48](https://cloud.githubusercontent.com/assets/3116038/11965507/32c3c108-a90a-11e5-873a-afd77970792e.png)

**Comment by aziz** [comment]
:+1:
