### ISSUE TITLE
مقدار ضخامت و فضای منفی برخی حروف

### ISSUE THREAD

**Issue by bhoutan** [rastikerdar/samim-font#2]
سلام
متوجه سختی یک پروژه طراحی حروف هستم و خیلی از زحمات شما ممنونم
حتی بهترین فونت های فارسی خالی از اشکال نیست 
(بعضی از حروف ضخامت بیشتری دارند (عـ
فضای منفی داخل (ص ق ف مم ههه) کمی نا متناسب است کمی هم بزرگ است
باز هم ممنونم

**Comment by bhoutan** [comment]
سلام
متوجه سختی یک پروژه طراحی حروف هستم و خیلی از زحمات شما ممنونم
حتی بهترین فونت های فارسی خالی از اشکال نیست 
(بعضی از حروف ضخامت بیشتری دارند (عـ
فضای منفی داخل (ص ق ف مم ههه) کمی نا متناسب است کمی هم بزرگ است
باز هم ممنونم

**Comment by rastikerdar** [comment]
سلام

احسنت بر شما
اغلب مواردی را که فرمودید بررسی و اعمال شد که در خوانایی فونت تاثیر به سزایی گذاشت.
مـ ـم ـمـ ف فـ ق قـ ق و ـو هـ ـهـ ه همگی اندکی کوچکتر و تمیزتز شدند.
حروف ع عـ نیز اصلاحات جزئی انجام شد.

لطفا نسخه 0.4 به بالا یا صفحه اصلی پروژه را مشاهده بفرمایید.

صـ و ـه را هر چه تغییر دادم بهتر نشد. نمی دانم شاید باز هم جا داشته باشد.
در مورد ضخامت حروف هر کدام به نظرتان ایراد دارد بفرمایید تا بررسی شود. بسیاری موارد تا حدودی عمدا این تغییر ضخامت از ضخیمی به نازکی (عمدتا برای خوانایی و تا حدودی زیبایی) صورت گرفته اما هر کدام که فکر می کنید اشکال دارد حتما بفرمایید.

سپاسگزارم از پیشنهاد بسیار خوبتان.

**Comment by rastikerdar** [comment]
اصلاحاتی بر روی حالات حروف ص ط نیز در نسخه 0.5 اعمال گردید.

**Comment by rastikerdar** [comment]
این ایشو رو با اجازه میبندم. اگر فکر می کنید نیاز به اصلاح است این ایشو را مجددا یا اینکه یک ایشو جدید باز بفرمایید. با تشکر
