### ISSUE TITLE
یکسان نبودن ارقام ۴ و ۵ و ۶ در مرورگر فایرفاکس و کروم

### ISSUE THREAD

**Issue by rastikerdar** [rastikerdar/samim-font#21]
دو گونه شکل از این ارقام در فونت موجود است. به نظر می آید گونه مناسب باید انتخاب و یکسان سازی انجام شود.
کدام ارقام خواناتر و زیباتر و همچنین مناسب رسم الخط فارسی می باشد؟

**Comment by rastikerdar** [comment]
فایرفاکس:
![digits-firefox](https://cloud.githubusercontent.com/assets/3116038/11178250/cc679bfc-8c60-11e5-8a8e-326906885e37.png)

کروم:
![digits-chrome](https://cloud.githubusercontent.com/assets/3116038/11178262/e762f5aa-8c60-11e5-9289-cc3fc224b290.png)

**Comment by artlesshand** [comment]
بالا عربیه و پایین فارسی

**Comment by rastikerdar** [comment]
پس طبیعتا فارسی رو باید انتخاب کنیم. یه دوست عزیزی هم به نام سید علی توی وبلاگ به عربی بودن این ارقام انتقاد کرده بودند که حق داشتند.

تشکر

**Comment by artlesshand** [comment]
متنی که با کیبورد استاندارد نوشته شده باشه رو باید بررسی کرد باهاش.

مرسی از شما

**Comment by ebraminio** [comment]
به نظر من هر دو را یکی نکنید، اگر چنین مشکلی وجود دارد احتمالاً راه حل دیگری دارد که می‌توان با دیدن سایر قلم‌ها آن را بررسی کرد. اگر می‌خواهید اعداد عربی-هندی را حذف کنید، به نظرم مشکلی نیست به این دلیل که حداقل با یکی از قلم‌های پشتیبان نمایش داده شود ولی یکی کردن آن‌ها فونت را حداقل برای کاربرد من نامناسب می‌کند که بر روی استاندارد بودن نگاشت نویسه به گلیف‌های موجود در قلم حساب می‌کنم

**Comment by rastikerdar** [comment]
وقتی گلیف های ارقام عربی رو حذف می کنم توی فایرفاکس از فونت سیستم (مثلا دژاوو یا تاهوما یا ...) استفاده می کنه که منطقی به نظر میرسه. نمی دونم چرا بین فایرفاکس و کروم تفاوت هست. توی گوشی هم همینطوره. 

به نظرتون چه فکری کنیم؟

**Comment by aziz** [comment]
این که برای من درست کار میکنه. 
مشکل از کجاست. بگو چی جوری این باگ رو باز تولید کنیم
<img width="966" alt="screen shot 2015-11-16 at 5 18 22 pm" src="https://cloud.githubusercontent.com/assets/3202/11187290/26398c4c-8c86-11e5-83a9-e04d532c362a.png">

**Comment by aziz** [comment]
Maybe your keyboard layout is wrong

**Comment by rastikerdar** [comment]
فکر می کنم از تنظیمات خود فایرفاکس باشه و گرنه بقیه جاها از جمله توی سیستم درست نشون میده.
بسیار خب پس به نظر خود فونت استاندارده و نباید دست بخوره.

**Comment by aziz** [comment]
@rastikerdar این ایشو‌ها که فیصله پیدا می‌کنه رو ببند تو رو خدا. یکی از بچه‌ها تو وزیر هم به این نکته اشاره کرده بود

**Comment by rastikerdar** [comment]
آخه هنوز توی برنچ اصلی کامیت نشده که با بگیم انجام شد. ببندیم قبلش یعنی؟

**Comment by aziz** [comment]
آخه این ایشو مثلا مگه تغییری داشته تو کد؟ اگه داشته که حق با توست

**Comment by rastikerdar** [comment]
ایشو رو می بندم ولی اگر کسی فکر می کنه نیاز به بررسی بیشتری هست حتما ایشو رو باز کنه.
