### ISSUE TITLE
donation

### ISSUE THREAD

**Issue by behdad222** [rastikerdar/samim-font#22]
یه روش برای دونیت کردن ایجاد کن :)

**Comment by aziz** [comment]
:+1: فقط هم برای ایران نباشه

**Comment by rastikerdar** [comment]
ببخشید به طور کلی برایم سوال پیش آمده.
آیا دونیت رو صرفا با هدف کمک به پروژه و برای صرف شدن توی خود پروژه دریافت می کنند؟
اگر بلی خب چجوری هزینه و گزارش می کنند؟

ممکنه کسی هم به صورت هدیه دریافت کنه؟ مثلا هر جوری خواست برای خودش مصرف کنه؟

**Comment by behdad222** [comment]
شما داری یه سری کارها میکنی که برای عامه مردم مفیده
هرکسی هم دوست داشته باشه میتونه بهت کمک کنه و شما هم به هر منظوری خرجش کنی

یه مورد دیگه هم هست
میتونی بگی مثلا اگر انقدر دونیت شد این کار رو میکنم مثلا یه فونت جدید میدم یا …
@rastikerdar

**Comment by aziz** [comment]
برای من مثل تشکر و قدردانی و هدیه است. تو وقت گذاشتی و این کار رو انجام دادی و اونو نه تنها رایگان که به صورت کدباز در اختیار دیگران گذاشتی من می‌خوام افراد بیشتری این کار رو بکنند پس به تو کمک می‌کنم هر طوری که باشه که کمک مالی هم یکی از اونهاست.
هر جوری که دوست‌داری می‌تونی خرجش کنی.

**Comment by rastikerdar** [comment]
ببخشید باز سوال می پرسم.
چجوری دونیت دریافت می کنند؟ من بعضا از طریق صفحه ای که طراحی شده بوده یا مستقیما به شماره حساب واریز می کردم. اصول خاصی داره که حتما باید رعایت بشه؟ اعلام شماره حساب کار ناپسندیه؟

یا مثلا اینکه عزیز جان فرمودند فقط برای ایران نباشه چجوری باید باشه؟

ببخشید کنجکاوی مرا.

**Comment by aziz** [comment]
در مورد ایران خیلی اطلاعی ندارم. خارج از ایران اگر پی‌پل داری میتونی اونو بدی تا دیگران برات پول بریزند. می‌تونی از یکی از فامیل‌ها و آشناها هم که کارت اعتباری دارند استفاده کنی و مثلا یه حساب تو 
gitpay.com
یا
pledgie.com
باز کنی..

**Comment by behdad222** [comment]
زرین پال خوبه

**Comment by artlesshand** [comment]
- راه آسونش باز کردن یه حساب و پرداخت پول کارت به کارتیه.
- راه سختش راه اندازی درگاه بانک در صفحه‌ی قلم مورد نظره.
- راه جدیدش هم پی‌پینگ هست (payping.ir)

**Comment by artlesshand** [comment]
البته راه @aziz برای خارجی‌ها هم خیلی خوبه. همون پی‌پل

**Comment by meysampg** [comment]
این هم میتونه گزینه‌ی مفیدی باشه.
https://2nate.com/
حتما سعی کن یه کانال برای دونیت ایجاد کنی.

**Comment by rastikerdar** [comment]
ببخیال برادرا اینجا ایرانه :)
با اجازه ایشو رو می بندم.

**Comment by zoghal** [comment]
اا چرا بیخیال؟
من پیشنهادم payping هست.

**Comment by rastikerdar** [comment]
گذاشتم صالح جان.
تقاضا می کنم کلا از این مسئله دونیشن عبور کنیم.
تشکر
