### ISSUE TITLE
عدد پنج فارسی

### ISSUE THREAD

**Issue by aziz** [rastikerdar/samim-font#23]
آقا این به نظر من زشت شده! حالا بقیه هم نظرشون رو بدند
<img width="79" alt="screen shot 2015-11-16 at 12 26 55 am" src="https://cloud.githubusercontent.com/assets/3202/11185673/2390bd7e-8c7e-11e5-8ec3-d84ca7db605b.png">

**Comment by rastikerdar** [comment]
یادم رفته برای چی اینجوری شده بوده.
این بهتره؟
![panj](https://cloud.githubusercontent.com/assets/3116038/11187129/6988dfac-8c9a-11e5-89f9-3efad805c025.png)

یا کلا شکلش زشته عوض شه؟

**Comment by aziz** [comment]
زبانه بالای پنج مهمه
یکان یکی از بهترین طراحی‌ها رو برای اعداد داره و برای همین اکثر سایت‌های بزرگ ایران از قلم یکان برای اعداد استفاده میکنند. البته همین یکان کمی دندانه پنج رو گند زده ولی کلا اعداد رو به سبک یکان دربیاری خیلی خوبه
ایران سن‌سریف هم خیلی تمییزه. به کرنینگ اعداد هم خیلی خوب توجه کرده
<img width="750" alt="screen shot 2015-11-16 at 5 23 44 pm" src="https://cloud.githubusercontent.com/assets/3202/11187475/d2ee55d0-8c86-11e5-999a-92407caee625.png">

**Comment by rastikerdar** [comment]
اینطوری؟
![panj2](https://cloud.githubusercontent.com/assets/3116038/11188564/bd776826-8ca0-11e5-9876-970070a413a6.png)

**Comment by aziz** [comment]
:+1:  خیلی بهتر شد

**Comment by rastikerdar** [comment]
یا این؟
![panj3](https://cloud.githubusercontent.com/assets/3116038/11188647/32c8842a-8ca1-11e5-95eb-147f632e0c9d.png)

**Comment by aziz** [comment]
من میگم اولی

**Comment by rastikerdar** [comment]
توی شاخه دولوپ 0.9.6 اعمال شد. متشکرم.
