### ISSUE TITLE
صفحه تست قلم

### ISSUE THREAD

**Issue by aziz** [rastikerdar/samim-font#24]
<p align='right' dir='rtl'>صالح (@zoghal) یک صفحه تست فونت فارسی درست کرده که شاید برای شروع خوب باشه
</p>

https://github.com/font-store/Persian-Font-Testing-Page

<p align='right' dir='rtl'>به نظرم اگه تو برنچ وب پیچ راهش بندازیم خیلی خوبه
</p>

<p align='right' dir='rtl'>
برای تاریخچه #13 را ببینید
</p>

**Comment by rastikerdar** [comment]
این خوبه اما خیلی مفصله. در کنار این یه دونه ساده یک صفحه ای هم که فقط اسکرول بخوره داشته باشیم که بشه سریع موارد مهم و رایج رو دید کار رو خیلی ساده میکنه.

**Comment by zoghal** [comment]
این رو یک ساعت پیش داشتم برای فونت ساز آماده میکردم. به کارتون میاد بگید بفرستم.
http://i.share.pho.to/82c38737_o.png

**Comment by rastikerdar** [comment]
اگر برایتان ممکنه مثل همونی که توی آدرس گیت هاب خانه فونت گذاشتین بزارید همه با هم استفاده کنیم. قشنگه.

**Comment by zoghal** [comment]
اوکی فقط میخواهید استاتیک ازش استفاده کنید یا  پویا.
مثلا اگر برای هر فونت بخواهید استفاده کنید. نیاز به جاوا اسکریپت و اینا نداره. یک سی اس اس رو تغییر میدید.
اما اگر بخواهید مثل اون تست فونت که گفتید شلوغ هست باشه مثلا دراگ و دروپ و همچین امکاناتی باید از الان بگید تو توسعه مد نظر داشته باشمش

**Comment by rastikerdar** [comment]
همین ساده برای شروع کفایت می کنه آقای سوزنچی.
اتفاقا همین ساده و ثابت باشه دیگه نیازی نیست با هر بار ریفرش فونت انتخاب کرد.

**Comment by zoghal** [comment]
خدمت شما.
انجام شد.
https://github.com/font-store/Perso-Arabic-font-specimen

**Comment by rastikerdar** [comment]
دست شما درد نکنه. جالبه باید برای قلم ها از این پروژه کلون کنم.

**Comment by rastikerdar** [comment]
برای شروع صفحه تست کامل یا همان اولی که عزیز فرمودند اضافه شد.
[تست](http://rastikerdar.github.io/samim-font/testing)

**Comment by zoghal** [comment]
خوبه تازه یک سری موارد مشخص شد ه‍ رو کمی بالا بکشید. فاصله دندانه های س‍ و ‍‍ـسـ یکسان و نزدیک بهم باید باشه وقتی یک شکل هستند.

**Comment by rastikerdar** [comment]
یعنی هـ رو به صورت عمودی بکشم بالا یا از خط کرسی ببرمش بالاتر؟
دندونه های سین چون اولش هدفم اندازه های نمایش ریز بود درشت گرفتم :)

البته یه فونت جدید طراحی کردم (غیر آزاد) توی اون تقریبا دندونه ها هم جمع وجورتر هم یه خورده کج کردم. ولی خب حس و حال نسخ رو داره این شکل دندونه. برای صمیم یه جور ترس از تغییرش هم داشتم. پیش خودم می گفتم احتمالا برای این سبک نباید این شکلیش کنم!
