### ISSUE TITLE
بهتر نیست گلیف‌های انگلیسی که فارسی نشدند حذف شود

### ISSUE THREAD

**Issue by aziz** [rastikerdar/samim-font#26]
شاید اطلاعات من در این زمینه کافی نیست. ولی بهتر نیست گلیف‌های اعداد انگلیسی و سیمبول‌ها که فارسی نشدند از قلم حذف شود همانطور که گلیف‌های حروف‌ انگلیسی حذف شده‌اند
![screen shot 2015-11-16 at 7 43 49 pm](https://cloud.githubusercontent.com/assets/3202/11191246/a879d504-8c9a-11e5-8881-d1fb406c736f.png)

**Comment by rastikerdar** [comment]
این برای خود من هم سواله. حذف کنیم بهتر نیست؟ که هر کی هر جوری دلش خواست بذاره؟

**Comment by artlesshand** [comment]
فکر کنم دو نسخه‌ای باشه خوبه.
یکی با گلیف‌های هم طراز و مناسب یه قلم آزاد، مثل اوپن سنس
و یکی هم فقط گلیف‌های فارسی،‌ که انگلیسی‌هاش رو یه فونت دیگه فال‌بک شه

**Comment by aziz** [comment]
موافقم ولی فونت فعلی اصلا گلیف‌های انگلیسی رو نداره. فقط اعداد و تعدادی علائم و نماد‌های نگارشی رو داره. 
من فکر کردم شاید دلیل خاصی داره که من اطلاعی ندارم. 

فکر کنم اگر یک بیلد اسکریپت باشه که تمام این واریانت‌های قلم رو جنریت کنه ساده‌تر می‌شه. چون همین‌حالا یک قلم هم برای جایگذاری غیراستاندارد اعداد انگلیسی با فارسی (که البته به نظرم کاری درستی نیست ولی دلایلش رو درک می‌کنم) وجود داره.

**Comment by rastikerdar** [comment]
توی فونت دروید عربیک نسخ دیدم کلا حذف کرده. واقعا وجودشون دردسر داره. چون شکل اعداد ممکنه مورد پسند همه نباشه یا علائم. اون چند تا نماد فارسی‌عربی خوبه بمونه اما سایرین رو توی برخی فونت ها دیدم هست برخی نیست. از اونجایی که این چند تا فونت سعی شده با فونت های انگلیسی هم تقریبا هم سایز باشه فکر نکنم نیازی به وجود شون باشه.
مگر اینکه همانطور که فرمودید نسخه های متعدد داشته باشیم.
صلاح رو در چی می دونید؟

**Comment by aziz** [comment]
به نظر من فعلا در این یکی حذف بشه. 
بعدا که بیلد اسکریپت و این حرف‌ها رو اضافه کردی می‌تونی یه نسخه دیگه هم باشه که دژاوو رو کامل داشته باشه بعلاوه‌ی این گلیف‌های فارسی. فعلا اولویت‌نداره. تازه حذفشون سایز قلم رو هم پایین میاره که واسه وب خیلی خوبه

**Comment by rastikerdar** [comment]
@aziz  @artlesshand 
پس اگر برایتان امکان دارد یه کوچولو بررسی بفرمایید کدام گلیف ها را از نسخه جدید کلا حذف کنم.
مثلا حالت فونت گندم خوبه؟ تعداد زیادی حتی نقطه و دونقطه هم حذف شده‌ اند.
یا اینکه مثلا علائم باشند و فقط اعداد حذف شوند؟

گیج شدم :(

**Comment by aziz** [comment]
یه بررسی می‌کنم و یک لیست دقیقتری رو پیشنهاد می‌دم.

**Comment by artlesshand** [comment]
به نظرم هر گلیفی که عدد و یا حرف هست حذف شه و باقی کاراکتر‌ها مثل نقطه و درصد و ریال  .. باقی بمونه. چون همنشینی‌ اونها در کنار حروف فارسی خیلی مهمه

**Comment by aziz** [comment]
این لیست پیشنهادی من برای حذفه
<img width="940" alt="samim" src="https://cloud.githubusercontent.com/assets/3202/11451367/7cfc89b6-95c4-11e5-94d4-0e61f369fdd8.png">

**Comment by artlesshand** [comment]
پس اینم پیشنهاد من از روی همین شکل

<img width="940" alt="7cfc89b6-95c4-11e5-94d4-0e61f369fdd8" src="https://cloud.githubusercontent.com/assets/763112/11451459/5c7a34b4-95dc-11e5-8667-23ae83ae1b96.png">

**Comment by rastikerdar** [comment]
چه کار قشنگی کردین. خیلی کار رو راحت کردین. دست شما درد نکند. مشترکات دو تصویر رو حذف می‌کنم تا برای بقیه هم به نتیجه برسیم.

@artlesshand علامت سوال انگلیسی که در فارسی کاربردی ندارد. دارد؟

**Comment by artlesshand** [comment]
نه ولی تو فکرم استفاده در یه عبارت با اعداد و غیره بود که تهش علامت سوال باشه، مثلا:

۱ + ۲ = ?

**Comment by artlesshand** [comment]
البته حق با شماست نیازی بهش نیست

**Comment by rastikerdar** [comment]
بالاخره از شر ارقام انگلیسی راحت شدیم.
اینها موند:
()*+/{}
البته فکر می کنم همین ها هم توی فونت به درستی همتراز نیستند. حالا باز بررسی کنیم ببینیم راهی برای اصلاحشون یا پیچوندن هست یا نه :P

**Comment by artlesshand** [comment]
:+1:

**Comment by rastikerdar** [comment]
فرزان توی نسخه 0.10 اون گلیف های که عزیز گفته بود رو حذف کردم. آخه قلم صمیم تلاش شده تقریبا با لاتین هماهنگ بشه که دیگه نیازی به این گلیف های غیر فارسی مثل اسلش و ... نباشه اگر چه استفاده میشه اما خیلی کمه و بیشتر با حروف انگلیسی به کار میره و اینکه خود کاربر هر چی دوست داره به عنوان فونت انگلیسی انتخاب کنه. همچنین حجم قلم بالا میره و توی ترکیبش با انگلیسی به هم میریزه. مثلا من نسخه ضخیمش رو که ساختم دیدم با لاتین اصلا ست نمیشه. مدیریتش هم دردسره. خلاصه فعلا حذف شد اما اگه به موردی بر خوردی که با فارسی جور در نمیاد بفرمایید حتما براش فکری می کنیم. مثلا یه نسخه در کنار اصلی همراه با گلیفهای علائم کاملا هماهنگ.

متشکرم بابت این ایشو و بحث ها و تصاویر.
