### ISSUE TITLE
 مدیریت نسخه های قدیمی قلم در سایت های دانلود مستقیم فایل

### ISSUE THREAD

**Issue by rastikerdar** [rastikerdar/samim-font#27]
این قلم ها توی چند تا سایت دانلود دیگه برای دانلود مستقیم از سرورهاشون گذاشته شده با اینکه هنوز در حال توسعه هستند.
از طرفی توی گوگل هم کسی مثلا بزنه فونت صمیم تنها موردی که نمیاره همین صفحه اصلی پروژه هست.
متاسفانه چون لینک هم نمیدن مخاطب فکر می کنه قلم همینه کلا با مشکلاتش!

این سایت ها نیتشون خیره اما نمی دونم این موضوع قابل مدیریت هست یا خیر.

**Comment by aziz** [comment]
به مروز زمان پیج رنک گیت‌هاب به اون‌ها غلبه ‌میکنه. به نظرم خیلی جای نگرانی نداره

**Comment by ebraminio** [comment]
می‌توانید از [این سایت](https://fontlibrary.org) استفاده کنید که نرم‌افزاری که از آن جهت ایجاد قلم استفاده می‌کنید  امکان ذخیره مستقیم در آن را دارد (البته ضرورتی ندارد لزوماً از آن قابلیت استفاده شود) ولی حداقل در [نتایج جستجوی من برای یک قلم](https://www.google.com/search?q=Iranian+Sans) معروف اول است

**Comment by rastikerdar** [comment]
این سایت خیلی خویه. خود من زیاد ازش استفاده کردم. اما مشکل اینه که قلم هایی که من تو اون سایت دیدم همگی کامل بودند. شاید مناسب نباشه یه قلم ناقص و در حال توسعه اونجا سایت ثبت بشه. گفتم یعنی صبر کرد تا یه به یه حد قابل قبولی برسه.
البته این نظر شخصی بود شاید اشتباهه.

**Comment by artlesshand** [comment]
همون لندینگ پیجی که ساختی خوبه و در نهایت هم گیت‌هاب خوب ایندکس میشه

**Comment by rastikerdar** [comment]
بسیار خب. ظاهرا نیازی به بررسی بیشتر نیست. سپاس از همه دوستان.
