### ISSUE TITLE
مشکل در نمایش ه دارای همزه به عنوان یک گلیف

### ISSUE THREAD

**Issue by aziz** [rastikerdar/samim-font#28]
<img width="409" alt="screen shot 2015-11-19 at 9 13 30 pm" src="https://cloud.githubusercontent.com/assets/3202/11282978/8f8abd96-8f02-11e5-8064-765defd255b4.png">

**Comment by rastikerdar** [comment]
دو گلیفش رو اضافه کردم البته نتوستم تست کنم.
اگر مشکلی بود ایشو رو باز بفرمایید.

با تشکر
