### ISSUE TITLE
راه حلی برای کوتیشن‌های مورب انگلیسی داریم؟

### ISSUE THREAD

**Issue by aziz** [rastikerdar/samim-font#29]
این رو باید چی کار کرد؟
<img width="81" alt="screen shot 2015-11-19 at 9 18 33 pm" src="https://cloud.githubusercontent.com/assets/3202/11283140/85ecc404-8f03-11e5-8038-764a98ac7013.png">

**Comment by artlesshand** [comment]
این کاراکتر فارسی نیست در اصل و معادلش همون گیومه میشه. در واقع باید در انگلیسی درست نشون داده بشه

**Comment by aziz** [comment]
آره درسته فکر کنم باید اول ملت رو آموزش داد چطور درست تایپ کنند

**Comment by artlesshand** [comment]
:+1:

**Comment by rastikerdar** [comment]
جالبه. پس من یه چیز جدید یاد گرفتم. گیومه صحیح تره. ممنونم
