### ISSUE TITLE
لیگچر الله هنوز قدیمی و به سبک قلم دژاوو است

### ISSUE THREAD

**Issue by aziz** [rastikerdar/samim-font#3]
<img width="153" alt="screen shot 2015-11-14 at 11 50 09 am" src="https://cloud.githubusercontent.com/assets/3202/11163186/fbbafdd2-8ac5-11e5-8d01-1094d4f6ab6b.png">

**Comment by rastikerdar** [comment]
اولا تشکر می کنم برای ایشو ها. خیلی خوشحال شدم که اینقدر دقیق بررسی نمودید و مورد به مورد گزارش فرمودید. ای کاش مشارکت دوستان بیشتر می شد.

در مورد لیگچر الله در واقع اصلا در فونت وجود ندارد. نتیجتا از فونت دژاوو بر روی سیستم شما استفاده شده که البته باید در فونت هم متناسب با سایر حروف قرار گیرد. حقیقتش کمی مردد بودم که شکل این لیگچر چگونه باشد. خاص یا معمولی با استفاده از سایر حروف.

**Comment by rastikerdar** [comment]
برای الله یک لیگچر ویژه ساختم به نظرتون خوبه؟

![allah](https://cloud.githubusercontent.com/assets/3116038/11169471/7fb7eb64-8bce-11e5-9cba-79f21aa23430.png)

**Comment by aziz** [comment]
به تنهایی زیباست. چند تا عکس از ترکبیبش در جمله در سایزهای مختلف هم کار قضاوت رو راحتتر می‌کنه

**Comment by rastikerdar** [comment]
در جمله:
![allah-in-middle](https://cloud.githubusercontent.com/assets/3116038/11170905/49973bce-8bf7-11e5-9393-42aba0299577.png)

**Comment by artlesshand** [comment]
فاصله‌ی تشدید با الف بالاش میتونه بیشتر شه و خود الف کوچکتر شه. نه؟

**Comment by rastikerdar** [comment]
الف همون اندازه الف اصلی هست. در واقع دو تا لام کوتاه تر شدند. منطقی اینه که لام ها را بلندتر کنم اما خب یه جورایی با حالت اریب از الف شروع شده و به ـه ختم شده.
فاصله تشدید هم درسته باید بیشتر بیشه البته فضا کم بود مجبور شدم.

**Comment by aziz** [comment]
به نظرتون اگر فشرده تر بشه یعنی فاصله دو تا لام و ه کمتر بشه بهتر نمیشه؟

**Comment by rastikerdar** [comment]
یه مشکل. کلمه الله اگر به تنهایی نوشته بشه ایرادی ندارد اما اگر با اعراب باشد مثلا (عِنْدَ اللَّهِ) به مشکل بر می خورد. واقعیتش بلد نیستم حلش کنم
:P
الان توی شاخه دولوپ هست و باز هم تلاش می کنم ولی اگر نشد موقتا بدون این ادامه میدیم تا راه حلش پیدا بشه

**Comment by aziz** [comment]
برای من که درست دیده میشه
<img width="782" alt="screen shot 2015-11-16 at 4 19 11 pm" src="https://cloud.githubusercontent.com/assets/3202/11185592/c6da3efc-8c7d-11e5-9830-3ba6afa97022.png">

**Comment by aziz** [comment]
آها این الله لیگچر نبود

**Comment by rastikerdar** [comment]
اضافه شد. البته برای اینکه وقت دوستان رو دوباره با تصاویر نگیرم همون نمونه ساده اولیه رو به صورت موقت گذاشتم.

با تشکر از شما
