### ISSUE TITLE
لیگاتور لا سنتی و عربی است

### ISSUE THREAD

**Issue by aziz** [rastikerdar/samim-font#30]
من شکل این لیگاتور لا رو دوست ندارم. دوست دارم بدونم دیگران چطور فکر می‌کنند. به نظر فرم ساده و عادی لا در «بلال» خیلی بهتره و با فرم و هویت قلم سازگاری بیشتری داری

<img width="582" alt="screen shot 2015-11-19 at 9 29 22 pm" src="https://cloud.githubusercontent.com/assets/3202/11283368/a093450c-8f04-11e5-93ed-f5893015b5ac.png">

**Comment by artlesshand** [comment]
موافقم
حتی لـا هم میتونه خوب باشه

**Comment by rastikerdar** [comment]
هر چند که قرار نیست زیادی به اصول و ضوابط خاصی پایبند باشیم مادامی که زیبایی و خوانایی در اولویت باشه اما به نظرتون اون لا وزیری برای این مناسبه؟ آخه اگر این فونت با هم طیف های خودش مقایسه بفرمایید همین لا استفاده شده. با حالت نسخ سازگاری بیشتری داره هااا. :)
اگر موافق باشین بیشتر بررسی کنیم از جنبه های مختلف.

**Comment by rastikerdar** [comment]
توی فونت گندم لا رو به همین شکلی که گفتید درآوردم. اگر خوبه توی صمیم هم بذاریم؟

[قلم گندم](http://rastikerdar.github.io/gandom-font/)

**Comment by aziz** [comment]
به نظر من که بهتر از این یکی حال حاضر در صمیمه

**Comment by rastikerdar** [comment]
راستش خیلی برای لا قبلی زحمت کشیده بودم :D
آخه شکلش پیچیده بود :)
این یکی چطوره؟
![la](https://cloud.githubusercontent.com/assets/3116038/11424485/da6569f0-9462-11e5-8552-130860712cac.png)

**Comment by aziz** [comment]
:+1:

**Comment by artlesshand** [comment]
ابهتر شد،‌ هرچند محل چسبیدن الف به به لام میتونه کمی کلفت‌تر شه

**Comment by rastikerdar** [comment]
انجام شد.
محل چسبیدن نیز ضخیم تر شد.

با تشکر
