### ISSUE TITLE
فشرده تر شدن قلم

### ISSUE THREAD

**Issue by rastikerdar** [rastikerdar/samim-font#32]
در موقع طراحی قلم تلاش می شد از منظر صفحات نمایش با کیفیت پایین پرداخته شود. یک دلیلش چسبیدگی یا در هم رفتگی حروف هنگام رندر است. اما خب از سویی با توجه با افزایش کیفیت صفحات نمایش و از سویی دیگر کوچک تر شدن اندازه آنها از جمله گوشی ها و نیاز به به استفاده بهینه از فضای موجود یا به عبارتی نیاز به افزایش تعداد کلمات در هر سطر و همچنین بهبود زیبایی به نظر می آید شاید تجدید نظر در اندازه ها انتظار به جایی باشد.

نظر شما چیست؟

**Comment by artlesshand** [comment]
به نظر من با کرنینگ درست و اصلاح گلیف‌ها مثل «رزژ» و «دذ» این اتفاق میفته که چیز خوبی هم هست.
اما اگر بخوایم خیلی فشرده‌سازی کنیم، نیاز به ساختن یک نسخه‌ی جدا به شکل کاندنس هست.

**Comment by rastikerdar** [comment]
درسته البته ر ز ژ فکر کنم بیشترین مشکل تو قلم باشند.

**Comment by artlesshand** [comment]
موافقم

**Comment by aziz** [comment]
به نظرم وزن قلم‌ها الان مهمتر از فشرده کردنشه. 
وزن ۱۰۰ و ۳۰۰ و ۴۰۰ و ۶۰۰ و ۷۰۰

**Comment by zoghal** [comment]
از همه مهمتر اینه که اول یک نمونه کامل آماده بشه و بعد از روزی اون وزن‌های دیگه گرفته بشه.
در مورد فشرده سازی هم باید بگم بر عکس حروف لاتین حروف فارسی زیاد امکان فشرده سازه یا کشیدگی حروف رو نداره. درحالت کلی کشیدگی و فشرده کردن حروف باعث دفرمه شدند گلیف ها میشه..

به این تصاویر نگاه کنید:
![14typeface](https://cloud.githubusercontent.com/assets/174688/11549895/843678b8-997f-11e5-9e27-574d7d99bfb2.jpg)
تناسب بین حروف بهم بخوره تو متن بیریخت میشه.
![e92da194835a8923c191d14338b4260f](https://cloud.githubusercontent.com/assets/174688/11549965/37e6ec76-9980-11e5-9a8b-b6e5791f2d80.png)
![b477b714c21b5c4f8002dbcb9d3663e4](https://cloud.githubusercontent.com/assets/174688/11549964/37e3b920-9980-11e5-81cb-442140e3e10a.png)

حروف ر ژ و ا ز اصطلاحا میگن کلمه رو از وسط قارچ میکنه.
برای جلوگیری از این مشکل
دو را وجود داره.
۱- استفاده از کرنینگ
۲- کم کردن فاصله از سمت چپ حروف تا نقطه که مناسب هست در کنارشون قرار بگیره.
راه اول راهکار استاندارد هست.
راهکار دوم عالیه ولی فکر کنم در یکی از سیستم عامل ها در شرایط خاص به مشکل خوردیم تو تستش. دفترم کنارم نیست. نگاه میکنم اطلاع میدم.
اما در کل بهترین کار کرنینگ هست.

**Comment by rastikerdar** [comment]
دست شما درد نکنه. البته توی این صمیم هر دو روش ناچارا با هم به کار رفته. حالا امیدوارم با شکل جدید ر آقا فرزاد مشکلات کمتر هم بشه.
@artlesshand

**Comment by rastikerdar** [comment]
خیلی خوبه توسعه این قلم صمیم به لحاظ آموزشی هم داره پربار میشه :)

**Comment by artlesshand** [comment]
@rastikerdar فرزان :)
ایشالا
