### ISSUE TITLE
تفاوت در زاویه شکستی و قوس کاف در حالت اتصال از چپ و راست

### ISSUE THREAD

**Issue by aziz** [rastikerdar/samim-font#33]
![kaf](https://cloud.githubusercontent.com/assets/3202/11518413/348b5ae8-9891-11e5-85f2-b8545dc3ec2b.png)

به نظرم در شکل بالا کاف شکل زیباتری از گاف داره. گاف هم باید شکل کاف وسط باشه

**Comment by rastikerdar** [comment]
موافقم کاملا.
کاف وسط قشنگتره. فراموش کردم کاف اول رو درست کنم.
این زاویه باید رعایت میشد.
این فونت دروید عربیک که خیلی ها دوست دارند برام خیلی عجیبه. من خودم دوست ندارم اما نمی دونم چجوری با این شکل عجیبش مورد پسنده!
![kak](https://cloud.githubusercontent.com/assets/3116038/11518976/5c07da82-98ab-11e5-9bd2-8cb0ad972dac.png)

**Comment by aziz** [comment]
دروید عربیک یک نسخ است که هیچ استروک صافی درش نیست کمی با صمیم صاف و صوف تو فرق می‌کنه

**Comment by zoghal** [comment]
@aziz عزیز ماشالله اینکاره ایی ها.
@rastikerdar دروید عربیک نسخ عربی هست. ما یک نسخ فارسی  داریم که بیشتر تو طراحی حروف سربی توسط استاد حقیقی مطرح شده(روی پروژه نازنین) مثل دندانه‌های مستقیم.
یک نسخ فارسی که به نسخ نیریزی معروف هست داریم که برای کتابت قرآن استفاده میشه.
در کل این فونت دروید عربیک باید گفت به نوعی نرمال هست بین هویت خط فارسی و عربی . به نوعی میشه گفت حد وسط هست.(نظر خودم هست.) برای همین مورد پسند هست. نه مثل نازنین استخوانی و خشک نیست
من بخش زاویه های کاف رو اتچ کردیم..
![kaf](https://cloud.githubusercontent.com/assets/174688/11549186/2f5407da-9979-11e5-8821-d6e07f7af1ba.png)

زیبایی حروف فارسی رو می تونید تو این مورد ببینید.
![kaf-dal](https://cloud.githubusercontent.com/assets/174688/11549615/ae50b5a8-997c-11e5-8b46-d5b7d6d0b544.png)

**Comment by rastikerdar** [comment]
خیلی خوب بود آقای سوزنچی.
من اون کاف توی تصویر شما رو خیلی بیشتر می پسندم. به ویژه اتصالش.

**Comment by zoghal** [comment]
خواهش میکنم. کاف فربد هست دیگه:)) 
آقا فربد جیگر بنده هستند فونتشم باید مثل خودش خوردنی باشه
. ، این فونت هدیه زادروز دو سالگی‌شون است. 
ممنون میشم این اقای سوزنچی رو به صالح تغییر بدید.

یادم رفت در مورد گ هم یک نکته هست. سر کج گاف از کاف میاد پایین در یک سطح نیستند

**Comment by rastikerdar** [comment]
![screenshot from 2015-12-23 00-00-45](https://cloud.githubusercontent.com/assets/3116038/11965535/5b40f326-a90a-11e5-9105-bc103f353530.png)

**Comment by zoghal** [comment]
:+1:
