### ISSUE TITLE
تغییر جزیی شکل قوس میم در دو حالت مختلف

### ISSUE THREAD

**Issue by aziz** [rastikerdar/samim-font#34]
![screen shot 2015-12-02 at 1 32 44 am](https://cloud.githubusercontent.com/assets/3202/11518806/c756d598-9894-11e5-812e-4bc60f9ce8a5.png)

به نظرم میاد دو میم باید شکل یکنواختی داشته باشند. تفاوتشان را می‌بینید؟

**Comment by aziz** [comment]
من میم اولی را بیشتر می‌پسندم

**Comment by zoghal** [comment]
:+1:

**Comment by artlesshand** [comment]
یکم سلیقه‌اییه به نظرم

**Comment by rastikerdar** [comment]
به نظرتون اینطوری بهتر نیست؟
![screenshot from 2016-03-04 02-46-38](https://cloud.githubusercontent.com/assets/3116038/13513023/73b181a0-e1b3-11e5-9a6c-cc4fec62fa9a.png)
