### ISSUE TITLE
گفتگو در مورد ادامه توسعه قلم

### ISSUE THREAD

**Issue by rastikerdar** [rastikerdar/samim-font#35]
در این ایشو به صورت اختصاصی در مورد ادامه توسعه قلم آزاد گفت و گو می کنیم. از دوستان گرامی تقاضا دارم که به مباحث غیر مرتبط نپردازند و البته به یکدیگر کمک کنیم این قلم را به سرانجامی برسانیم.

**Comment by rastikerdar** [comment]
@aziz 
[ماهی‌گیری](http://rastikerdar.github.io/getting-started-with-fontforge/)

**Comment by aziz** [comment]
عالیه این. دستت درد نکنه

**Comment by ebraminio** [comment]
عالی بود. ممنون

**Comment by ebraminio** [comment]
پیشنهاد می‌کنم متن این آموزش و به همراه تصاویر خودتان را به مجوز
CC-by-SA 3.0
 https://creativecommons.org/licenses/by-sa/3.0/
نیز قرار دهید که مشابه جی‌اف‌دی‌ال است (می‌توانید دو مجوز را همزمان نیز داشته باشید) تا بشود آن را در ویکی‌کتاب
https://fa.wikibooks.org
نیز قرار داد

**Comment by zoghal** [comment]
:+1:  بسیار عالی
پیشنهاد: مباحث رو دستبندی کنید بهتر میشه. خیلی شلوغ هست.

**Comment by rastikerdar** [comment]
@ebraminio 
اضافه شد. ممنون

@zoghal 
حق با شماست. پیشنهاد خوبیه. باید یه دسته بندی مناسب براش پیدا کنم همراه با فهرست. ممنون

**Comment by ebraminio** [comment]
با تشکر، [انجام شد](https://fa.wikibooks.org/wiki/%D8%B7%D8%B1%D8%A7%D8%AD%DB%8C_%D9%82%D9%84%D9%85_%D8%A8%D8%A7_%D9%81%D9%88%D9%86%D8%AA%E2%80%8C%D9%81%D9%88%D8%B1%D8%AC)

**Comment by rastikerdar** [comment]
دست شما درد نکند.

**Comment by zoghal** [comment]
@ebraminio  :+1:

**Comment by msm1365** [comment]
قلم خوبیه، ولی یک حالت فانتزی داره که برای کارای رسمی مانند مجله و وبسایت های آموزشی شاید مناسب نباشه البته مطمئن نیستم.

توی فونت ها صمیم و شبنم می پسندم فکر میکنم بقیه حرف خاصی یا ویژگی خاصی برای گرفتن ندارن

شبنم یه یکان نزدیکه واقعا حیف یکان که لایسنس و سورس نداره حیف خیلی قلم خوبیه

همه فونت ها توی اندازه های کوچک مانند 10 به نظرم خوب نیستند شایدم توقع من زیاده
الیته فونت هایی مثل دروید گوگل هم تقریبا همین طور هستند اما در ابعاد کوچک نمایش بهتری دارند
اما در اندازه های بزرگ نمایش خوبی دارند

**Comment by rastikerdar** [comment]
سلایق متفاوته. یکی میگه پرستو از این چند تا بهتره یکی وزیر ...

در مورد قلم ها حقیقتش سه مشکل وجود دارد:

اولا من تخصصی در زمینه فونت ندارم.

همچنین چون چند تا فونت تقریبا همزمان شروع شد طبیعتا مدیریت و رسیدگی به آنها خیلی مشکل میشه. البته این به امید آن بود که مشارکت ها به نسبت سلیقه در بهبود فونت ها بیشتر شود که نشد. فونت های دیگر چند یا چندین برابر این مقدار کار شده اند. فردی یا گروهی. آنهم با هزینه های کلان و عموما به سفارش شرکت یا سازمانی. متاسفانه هیچ گونه سند یا الگو یا تاریخچه ای از دیگر فونت ها وجود نداشت که من بتوانم از آن در توسعه فونت‌ها استفاده کنم. همه چیز در تاریکی مطلق!

و خب در آخر از کار رایگان در ایران شاید نشه بیش از این انتظاری داشت چرا که آنقدر انگیزه های غیر مالی باید وجود داشته باشه که فرد رغبت کند به کار خوب. متاسفانه این انگیزه های غیر مالی در این حقیر علی‌رغم دعوت بسیار از همگان به وجود نیامد. تنها دو نفر از دوستان مشارکت نمودند. شاید دلیل اصلیش بد بودن فونت ها بود.

راستشو بخواهید من فکر می کردم استارتی می زنم و بقیه خودشون کار رو به دست می گیرند یا در واقع کل فونت ها واگذار میشه به دوستان و من می تونم از پروسه خارج بشم اما خب خیالی خام بود.

من این اطمینان را به شما می دهم فونت کمپین قلم آزاد آن چیزی که مد نظر شماست یعنی فونتی برای تقریبا همه زمینه ها اعم از رسمی و غیر رسمی را برآورده می کند. چون تصویر اولیه ای که از آن منتشر شد نوید همچنین حالتی رو میداد. کمی صبر کنید.

در مورد اندازه‌های کوچک چون من فکر نمی کردم اندازه ۱۰ مورد استفاده قرار گیرد توجهی نکردم. زیر 11 جایی ندیدم. نمی دونم کجا این اندازه استفاده میشه. البته منظورم برای صفحه نمایش است. برای چاپ که من حتی یک مورد پرینت هم از این فونت ها ندیدم که بدونم اوضاع چگونه است. البته  این روزها کیفیت صفحات نمایش اینقدر بالا رفته که اندازه ۵ هم نمایش مطلوبی دارد. فکر می کنم مانیتور بنده بی کیفیت ترین می باشد با ۹۶ پی پی آی.

به هر صورت عذرخواهی می کنم.

ممنونم بابت نظر.

**Comment by rastikerdar** [comment]
@behdad222
آقا بهداد عزیز این تصویر جدید قلم آزاد واقعیت داره؟ یعنی کلا این شکلیه؟ ظاهرش رو منظورمه نه خرده کاریش!

**Comment by behdad222** [comment]
بزارید تا چند دقیقه دیگه تغییراتی هم که امروز دادیم رو اضافه میکنم و عکس میزارم

**Comment by behdad222** [comment]
@rastikerdar 
![screenshot from 2015-12-26 23 51 29](https://cloud.githubusercontent.com/assets/3942191/12007828/06d33306-ac2c-11e5-8b40-1eff5e8bfe7f.png)
![screenshot from 2015-12-26 23 53 56](https://cloud.githubusercontent.com/assets/3942191/12007829/06fd0e9c-ac2c-11e5-9d38-9ec411607daa.png)

**Comment by rastikerdar** [comment]
@behdad222
به شخصه به عنوان یه فرد معمولی این با آن چیزی که فکر می کردم یا انتظار داشتم زمین تا آسمان توفیر دارد. 
پیشنهاد می کنم برای ادامه توسعه حتما با متخصصین فونت یا گرافیست ها مشورت کنید یا از مردم نظرخواهی کنید.
به هر روی هر طور خودتان صلاح می دانید. اگر هم مایل بودید در موردش می تونم توضیح بدم البته از منظر یه فرد معمولی.
ولی خب اگر پاسخ جامعه یا بازخوردها مثبت بوده که هیچ.

موید باشید

**Comment by zoghal** [comment]
@rastikerdar  خوب شما نظرت رو بگو من دوست دارم بدونم نظرت چیه؟!
@behdad222  بهدادجان دامون خودش تکمیلش رو اعلام کرده. کی از مخزن رونمایی میشه؟

**Comment by rastikerdar** [comment]
@zoghal نپسندیدم صالح جان :)

**Comment by msm1365** [comment]
نتیجه فونت آزاد اگه این باشه خیلی افتضاحه

**Comment by behdad222** [comment]
@zoghal نه هنوز

**Comment by rastikerdar** [comment]
تا الان برداشت من اینه که جو بین بچه های حوزه های مختلف هنری به ویژه گرافیک زیاد جالب نیست و هر کسی فقط خودش و سبکشو قبول داره. اینو با یکی از بچه های کارشناس ارشد گرافیک در مورد گرافیک صحبت می کردم زیاد تاکید می کرد. به نظر توی فونت هم همینجوره. حتی در صورت ابراز تمایل هم ظاهری بوده و قلبا دیدگاه منفی هست. کار هنری همینه. هیچ موقع دو سلیقه کاملا یکی نمیشن. متاسفانه توی ایران نگاهشون به این اختلاف سلیقه منفی هست و به آن احترام نمی گذارند.  متوجه نمیشن این تنوع خودش زیباست. مثل گنولینوکس با توزیع های مختلف. اما فرهنگ گنولینوکسی کجا آن کجا!

@aziz @artlesshand @ebraminio  @behdad222 @zoghal @msm1365
اگر فرصت کردید این صفحه رو ببینید. به نظرتون فونت پرستو نسبت به روز اولش بهتره شده یا خیر؟ همچنین از دیدگاه فردی که صرفا سطحی میخواد یه مطلبی بخونه و حواسش به جزيیات فونت نیست چطوره؟ اصلا میتونید راحت مطلبو بخونید؟

[parastoo-font/computer.html](http://rastikerdar.github.io/parastoo-font/computer.html)

**Comment by aziz** [comment]
به نظرم خوانا است ولی خوشگل نیست. نمی‌تونم ایراد‌های مشخصی بگیرم ولی به دلم نمی‌شینه. 
شاید به دلیل شباهت‌هایی که با قلم‌های چاپ سنتی پیدا کرده. 
یک ناهمگونی هم داره که هنوز نمی‌فهم از کجاست.

**Comment by msm1365** [comment]
مهمترین مشکل فونت های جدید به نظرم اینه که زیبا و چشم ربا نیستند.
رنگش هم کمه نمیدونم مربوط به فونته یا رنگ انتخابی استایل

البته در خوانایی مشکلی نداره

**Comment by msm1365** [comment]
فونت شبنم را برای بخشی از سایت قرار دادم. اندازه بزرگ به نظرم خوبه اما اندازه کوچیکتر که گذاشتم دقیقا نمیدونم ولی چشم ربا نیست
 http://www.truckdriver.ir/
زیر منوی اصلی بخش مطالب ویژه فونت شبنم گذاشتم

**Comment by rastikerdar** [comment]
البته این مشخصا می خواست به حالت چاپ نزدیک بشه. موافقم من هم همین مشکل رو با زیباییش دارم. خوشگل نیست. ببینم چه ترفندی می تونم براش بزنم.

**Comment by rastikerdar** [comment]
رنگش هم فکر می کنم به خاطر سایز فونت هست. تنظیم نیست.

**Comment by rastikerdar** [comment]
@aziz  @msm1365 
یه سری تغییرات دادم ببینید احساستون بهتر نشده؟
[parastoo-font/computer.html](http://rastikerdar.github.io/parastoo-font/computer.html)

**Comment by msm1365** [comment]
البته این رنگ کمش که کلا توی ذوق میزنه

اگه مشکی پررنگ تر بود بهتر بود

یه جاهایی به نظرم نیاز به بازبینی داره البته من متخصص فونت نیستم

مثلا حرف ر خیلی ایستاده است و شاید بهتر بود کمی بیشتر قوس داشت

حرف ر ترکیبی با جمله خیلی نزدیک به کلمه قبلی است مثلا کلمه دیگری حرف ر خیلی به گ نزدیک است

یا در کلمه میکرو باز حرف ر به نظر خیلی نزدیکه به ک هست

مثلا در کلمه سخت‌افزاری حرف ز باز نزدیک است و ایستاده است

با این حال به نظر من از نظر خوانایی مشکلی نداره

**Comment by zoghal** [comment]
@aziz به نظرم چون کمی تمایل به NotoNaskhArabic-Regular پیدا کرده مخصوصا در سین  این شکلی به نظر میاد.

چند ایراد رو اسکچ کردم.
![dsc01241](https://cloud.githubusercontent.com/assets/174688/12025207/7fddf84e-adc1-11e5-8581-5cba43c0fe4e.jpg)
![dsc01242](https://cloud.githubusercontent.com/assets/174688/12025213/8575d984-adc1-11e5-869b-7ac3ff524b79.jpg)
![dsc01243](https://cloud.githubusercontent.com/assets/174688/12025214/87fec47c-adc1-11e5-8e89-4f8c9fb91907.jpg)

**Comment by zoghal** [comment]
![dsc01240](https://cloud.githubusercontent.com/assets/174688/12025298/7bedbb88-adc2-11e5-8926-1e85fdd5ea91.jpg)
![dsc01236](https://cloud.githubusercontent.com/assets/174688/12025296/7abee16a-adc2-11e5-9616-91916aa674de.jpg)
![dsc01237](https://cloud.githubusercontent.com/assets/174688/12025291/717144cc-adc2-11e5-9c2a-5c2449ff1572.jpg)
![dsc01238](https://cloud.githubusercontent.com/assets/174688/12025292/717b7fc8-adc2-11e5-8550-45683ed5d740.jpg)
![dsc01239](https://cloud.githubusercontent.com/assets/174688/12025293/717bb8d0-adc2-11e5-828e-40d8b105ac9f.jpg)

**Comment by rastikerdar** [comment]
@msm1365
یه بازنگری کلی هم توی گلیف ها هم توی سایز و ضخامت فونت کردم. حسابی پررنگش کردم. قوس ر رو بیشتر کردم. نمی دونم برای شما هم معلومه یا نه

[parastoo](http://rastikerdar.github.io/parastoo-font/)

[test](http://rastikerdar.github.io/parastoo-font/test.html)

@zoghal 
دست شما درد نکنه. راستی از فونت فربد چه خبر؟ رهاش نکنی یه موقع! میخوای آزاد منتشر کنی؟

**Comment by zoghal** [comment]
@rastikerdar خوب شده اما مشکل زیاد داره. فکر کنم شما داری روی سایز ریز بیشتر کار می‌کنی. چون وقتی سایز رو زیاد می کنی یکسری ناهماهنگی‌ها مشخص می‌شه که دلپسند نیست..
 عمده مشکلی که می بینیم تو فونت پرستو این هست که شما هیچ دیدی نسبت به قلم و حرکت قلم ندارید. تو این سبک که از نسخ و سایر دستگاهای خط‌ فارسی بهره گیری میشه در طراحی فونت، بسیار ظریف کاری داره. و تا زمانی که به خود خط و خوشنویسی حروف آشنا نباشی ۹۰٪ به بیراهه میرید.
همین الان دارم یک فولدر به مجموعه کتابخانه ای که پیرامون خط فارسی جمع کردم اضافه میکنم به اسم دستگاه‌های خط فارسی حتما نگاهش بنداز اللخصوص نسخ رو 
لینک : https://drive.google.com/folderview?id=0B63aUENCmKIOUkhPMTE2c0JlZ28&usp=sharing

**Comment by zoghal** [comment]
@rastikerdar در مورد فربد آره آزاد هست. نه بابا فقط یک مشکلی هست این هست که وابسته به سیستمی که طراحی کردم. وابسته باهم هستند فعلا زمانی فونت کامل میشه که rfb کامل بشه و بلعکس.
جناب رستگار من چند مورد هست میخواهم خصوصی باهاتون در میان بزارم. دعوت چت تو جیمیل فرستادم مونده رو هوا میشه این ارتباط رو بر قرار کنید.

**Comment by rastikerdar** [comment]
فونت پرستو 0.8.1 رو در قسمت خط پایه یه مقدار نازکتر کردم. چندتا گلیف رو هم اصلاح کردم از جمله سین و میم و کاف. اگر فرصت کردید دوباره ببینید.
دیگه فکر می کنم پرستو به ریل خودش افتاده. درسته خرده کاری کم نداره اما خب توی این مدت تلاش کردم پرستو یه شکل اولیه منسجمی به خودش بگیره که فکر می کنم الان نزدیک شد. هدفم یه قلم جدید از خانواده نازنین و میترا و زر و امثالهم برای وب بود که فکر می کنم بهش رسیدم. خدا رو شکر الان خیالم راحته که دیگه دغدغه ای در مورد ظاهر اصلی یا به نوعی ریل توسعه این فونت ها ندارم به جز نسخه ضخیم پرستو و همچنین گندم و تنها که سر فرصت بهشون می رسم. البته یکی دوتا تا فونت کاملا متفاوت دیگه هم در ذهن داشتم که به نظرم جالب میشد حتی برخی گلیفهاش رو طراحی کردم ولی خب دیگه کشش جسمی و زمانی نداشتم رهاش کردم.

از همه دوستان به ویژه عزیز (آلن برگی) مهربان، باحوصله و صبور نیز متشکرم و عذرخواهی می کنم بابت این پیام های توی ایشوها که مزاحم دوستان می شدم. یه لیست کامل از همه دوستانی که در توسعه قلم ها مشارکت فرمودند تهیه و منتشر می کنم و ازشون قدردانی می کنم. تنها کاری که از دستم بر میاد همین هست. بالاخره تلاش شد یه چند تا قلم کوچولو به دنیای فونت فارسی اضافه بشه.

در مورد کمک های نقدی هم تا به اکنون مبلغ ۲۵ هزار تومان کمک گردیده که اولا تشکر می کنم ثانیا انشاءا.. که راضی باشند. چون می دونم این فونت ها کامل نیستند و هنوز با انتشار نهایی فاصله زیادی دارند اما با این وجود محبت کرند. حلالم کنند.

یه گزارش کوچولو بود. توسعه قلم ها نیز به تدریج با کمک دوستان ادامه می دهیم.

به دوستان کمپین قلم آزاد هم خداقوت می گویم و هم توصیه می کنم درگیر مسائل حاشیه ای نشوند و فقط بر روی کارشان متمرکز باشند.

**Comment by rastikerdar** [comment]
@zoghal 
آقای صالح عزیز. پرستو بنا نبود بهترین فونت دنیا بشه. شما توی این صفحه با این ورژن جدید 0.8.1 پرستو یه نگاهی بندازین و مقایسه بفرمایید:
[compare](http://rastikerdar.github.io/compare-fonts/)
آیا به نظر شما پرستو در کنار قلم های زیبای نازنین و میترا هیچ حرفی برای گفتن ندارد؟
حالا ۹۰٪ خیلی نیست؟ یه کم تخفیف بده برادر. ;)
در مورد مطلب چکیده ای که گذاشتید اون قسمتی که نوشتید جامعه در حال فراموش کردن هویت اصلی خط فارسی است رو خیلی پسندیدم. به هر حال هیچ گاه نباید ناامید شد.
در مورد چت راستش من زیاد اهل چت نیستم. اما با ایمیل خیلی راحتم. ولی در مورد دعوت چت به روی چشم در خدمتم.

**Comment by zoghal** [comment]
:)) ای بابا مگر ما بهترین هم داریم!! بهترین بودن حد و حدودی نداره، باید سعی کرد شاید به بهترین حالت دست پیدا کرد.
اما بهترین بودن در یک فونت به نظرم شرایتی است که فونت در بیشترین کاربرد‌ها و مصرف کننده‌هاش مورد تایید و استفاده قرار بگیره.
این رو خودتون تو فوتوشاپ امتحان کنید. و بدید چند نفر دیگه بجز وب استفاده کنند و نظر بدن.
اما در مورد مقایسه، مقایسه تو این حالت واقعا اشتباه هست. نازنین و میترا هر دو برای حروف سربی و خداسال پیش طراحی شدند. اصلا ظرافت‌های لازم رو ندارند. و متاسفانه به دلیل نبود فونت مناسب دارند استفاده می‌شوند.
در کل به نظر من خیلی جای بهتر شدند داره. نمیگم بده ها، جای بهتر بهتر شدند داره.
یک جک فونتی بگم : فونت هولیتیکا ده ساله داره بروزرسانی میشه و هر دفعه بهتر و بهتر میشه. و نتیجه : فونت در طول زمان جا میوفته. :)

خواهش میکنم. از این بع بعدش رو باید بخونی از امروز سوکوتم رو مشکنم و مینویسم. http://saleh.soozanchi.ir/ در مورد همین فونت و داستانها کارهایی که کردم و درگیرهایی که داشتم.....

**Comment by rastikerdar** [comment]
راستش صالح جان من از حرف های شما زیاد سر در نمیارم! پرستو فقط برای وب طراحی شد. حالا اگر جای دیگری هم بشه استفاده کرد که چه بهتر. نشد هم مشکلی نیست چون وب هدف اصلیش بود. پیشنهاد می کنم یه بار دیگه اون صفحه مقایسه رو ببینی واقعا پرستو آیا هیچ حرفی برای گفتن ندارد؟ نیازی هم نیست اینجا پاسخ بدی. تو دلت بگو ;)

در مورد شکستن سکوتت خدا به همه رحم کنه! آقا من توی هیچ ماجرایی نقش نداشتم هاااا! هیچ کسی رو هم نمیشناسم :D
نظر منو بخوای میگم بیخیال این حرف ها شو و فقط به کار فکر کن.

**Comment by zoghal** [comment]
خوب اگر فقط برای وب فقط باشه، که عالیه اقا همه هم که راضی هستند، بریم مرحله بعد؟ بقیه هم هستند‌ها!!! 

```
جامعه در حال فراموش کردن هویت اصلی خط فارسی است
```

فراموش نشه جامعه فقط وب نیست، بقیه هم هستند جامعه ویراستارها و نویسنده‌ها، گرافیست‌ها، ناشرین، 

اتفاقا یک نقش واسط کنار گذاشتم تو بخش تقدیر و تشکر‌ها، می‌خوای بزارمت تو بخش طراح‌های حروف :دی

**Comment by rastikerdar** [comment]
اگر چه هنوز قلم پرستو خیلی جای کار داره و شاید هم هیچ وقت به درد نخوره اما واقعا نسخه اولیه پرستو خیلی داغون بود! بیچاره دوستان که تحمل می کردن پست های منو!

old:
![parastoo](https://cloud.githubusercontent.com/assets/3116038/14012445/64aeaaaa-f1c3-11e5-9886-24f15c8eb7cb.png)

new:
![screenshot from 2016-03-24 13-17-30](https://cloud.githubusercontent.com/assets/3116038/14012448/6b5b69ce-f1c3-11e5-95c2-916c373c79b8.png)

![screenshot from 2016-03-24 13-25-15](https://cloud.githubusercontent.com/assets/3116038/14012538/f0072640-f1c3-11e5-885e-7d316c8b297f.png)

:P :D

**Comment by aziz** [comment]
پرستو هم به جای خوبی رسیده. خسته نباشی و دست مریزاد
