### ISSUE TITLE
تغییر شکل الف متصل به لام

### ISSUE THREAD

**Issue by rastikerdar** [rastikerdar/samim-font#36]
قبلی:
![screenshot from 2015-12-23 00-08-27](https://cloud.githubusercontent.com/assets/3116038/11965402/73ebd0d6-a909-11e5-9297-5a566553d37e.png)

جدید:
![screenshot from 2015-12-23 00-08-35](https://cloud.githubusercontent.com/assets/3116038/11965404/76e0f06e-a909-11e5-94b7-a0c1cbf6f472.png)

@aziz  @artlesshand

**Comment by aziz** [comment]
:+1:  خوبه تغییرش فکر نکنم در سایز کوچیک به چشم بیاد البته
