### ISSUE TITLE
تغییرقوس ع ح

### ISSUE THREAD

**Issue by rastikerdar** [rastikerdar/samim-font#37]
قدیم:
![screenshot from 2015-12-23 00-23-31](https://cloud.githubusercontent.com/assets/3116038/11965691/8201acfc-a90b-11e5-9921-40a0c6bea815.png)

جدید:
![screenshot from 2015-12-23 00-23-40](https://cloud.githubusercontent.com/assets/3116038/11965693/89e76f60-a90b-11e5-8c43-404654f1a4f8.png)

@aziz  @artlesshand

**Comment by aziz** [comment]
:+1:  
ح و ع خیلی خوب شده
یک مشکلی در دو طرف اتصال ف هست میبینی؟

**Comment by rastikerdar** [comment]
فکر می کنم منظورت اون ناحیه تیره تر هست. تو این قسمت گلیف ها در هم فرو رفتند. یه جور فضای اطمینان که در زمان رندر از هم جدا نشون نده. تقریبا همه حروف متصل به هم دارند. یه راهش اینه که اون ناحیه گرد بشه مثل فونت های دروید و ... اما خیلی زحمت داره
:(
