### ISSUE TITLE
شکل مد الف

### ISSUE THREAD

**Issue by rastikerdar** [rastikerdar/samim-font#38]
قدیم:
![screenshot from 2015-12-23 00-45-02](https://cloud.githubusercontent.com/assets/3116038/11966058/795abe2e-a90e-11e5-9c94-15efb77d0b95.png)

جدید:
![screenshot from 2015-12-23 00-44-53](https://cloud.githubusercontent.com/assets/3116038/11966060/7aed1c28-a90e-11e5-8ce8-d72b8744c351.png)

@aziz  @artlesshand

**Comment by aziz** [comment]
به نظرم قبلی برای صمیم مناسب‌تره. این شکل جدید بیشتر به درد شبنم می‌خوره

**Comment by rastikerdar** [comment]
موافقم
نمی دونم چرا برای این گذاشتم! اون بالایی رو یه کم بهترش می کنم.

**Comment by zoghal** [comment]
می تونی کمی دایره ها رو به ضلع تبدیل کنی  در تغییر جهت ها. فکر کنم بهتر بشه.

**Comment by rastikerdar** [comment]
سعی می کنم دو سه حالت درست کنم یکی انتخاب کنیم.

**Comment by zoghal** [comment]
![dsc01250](https://cloud.githubusercontent.com/assets/174688/12025180/42651524-adc1-11e5-85bc-5b73513ab950.jpg)

**Comment by rastikerdar** [comment]
ممنونم صالح بابت تصویر. خیلی قشنگه. به ویژه یکی بالا سمت راست و سمت چپ
