### ISSUE TITLE
مشکل در نمایش حرف ش

### ISSUE THREAD

**Issue by meysampg** [rastikerdar/samim-font#39]
به دو تصویر زیر دقت کنید:
![screenshot_2015-12-23_10-20-37](https://cloud.githubusercontent.com/assets/1416085/11972248/db73bd72-a95e-11e5-94ec-e9822a719e90.png)
![screenshot from 2015-12-23 10-19-52](https://cloud.githubusercontent.com/assets/1416085/11972247/db739efa-a95e-11e5-8cde-3f3b60a83e08.png)
کلمه‌ی «پذیرش» در دو مورد دارای نقطه‌های ریزتر از حرف در نمایش‌ه. به نظر شما مشکل از چی میتونه باشه؟ این مشکل روی آخرین نسخه‌ی فایرفاکس و کروم که روی سیستم‌عاملم دارم، به صورت مشابه وجود دارن.

**Comment by rastikerdar** [comment]
در نسخه ۰.۹.۹ این مشکل رفع شد.
البته پیشنهاد من استفاده از نسخه جداگانه ضخیم است چرا که کارهای زیادی بر روی آن صورت گرفته. بولد کردن توسط مرورگر خروجی نازیبایی در پی دارد. برای مثال نمونه های زیر را ببینید:

ضخیم شدن توسط مرورگر یا برنامه:
![screenshot from 2015-12-23 13-33-14](https://cloud.githubusercontent.com/assets/3116038/11974494/e4f2030c-a979-11e5-9d69-0053e6dc0b03.png)

نسخه جداگانه ضخیم: Samim-Bold
![screenshot from 2015-12-23 13-30-40](https://cloud.githubusercontent.com/assets/3116038/11974502/f7e5d9a2-a979-11e5-97a5-4f309324c92a.png)

از شما بابت گزارش ایراد حرف شین سپاسگزارم.

**Comment by meysampg** [comment]
ممنونم!
