### ISSUE TITLE
اتصال طا و ظا به الف نیازمند یک لیگچر مجزا است

### ISSUE THREAD

**Issue by aziz** [rastikerdar/samim-font#4]
<img width="64" alt="screen shot 2015-11-14 at 11 50 21 am" src="https://cloud.githubusercontent.com/assets/3202/11163191/2085c084-8ac6-11e5-816a-f56b8d9f13ca.png">

**Comment by rastikerdar** [comment]
اشاره نفرمودید که شکل آن باید به چه صورت باشد؟ راستش من نتونستم مشکل رو پیدا کنم.

**Comment by aziz** [comment]
<p align='right'>به نظرم باید کمی فشرده تر شود و فاصله دسته طا با قوسش کمی کمتر شود</p>

**Comment by zoghal** [comment]
در فارسی فقط لا لیگچر هست. و دیگر لیگچری نداریم. گلیف باید تصحیح شود.

**Comment by aziz** [comment]
درسته در این مورد مشکل جزئی در گلیف‌ها وجود داره. 
ولی این مطلب که در فارسی فقط لا لیگچر هست خیلی به نظرم درست نمیاد. 
این رو من در متن اون پرشین هیگ که هومن مهر نوشته بود هم خوندم ولی به نظرم توصیه نامناسبی اومد. شاید البته من درست نفهمیده باشم. قلم ایرانیان‌سنز هومن مهر تا جایی که یادمه لیگاتورهای مجزا برای اتصال سین و یا داشت.
لیگاتور بسته به سلیقه طراح می‌تونه به قلم اضافه بشه. اما می‌تونیم اینطوری بگیم که توصیه می‌شه تمام قلم‌هایی که برای فارسی طراحی میشوند حداقل لیگاتور لا را داشته باشند.

**Comment by zoghal** [comment]
ببینید دو تا بحث هست:
۱- الفبا : که ما اینجا فارسی صداش میکنیم. در الفبای فارسی لا هم نداریم. فقط در کیبورد استاندارد که اون هم از ماشین تایپ گرفته شده اضافه شده.
۲- خط : وقتی بحث خط و کالیگرافی وسط میاد داستان فرق می‌کنه مثلا نستعلیق پر از ترکیب هست یا لیگچر . من شمردم چندتا از حروف رو کمتر از ۱۵ حالت مختلف با حروف بعدی شون دارند.
![56](https://cloud.githubusercontent.com/assets/174688/11523647/3dbd97f0-98d9-11e5-8e40-6ecdbac5a195.jpg)
![61](https://cloud.githubusercontent.com/assets/174688/11523648/3dbdfbbe-98d9-11e5-997c-8a51d4a64d42.jpg)

آنچه شما اشاره کردید در فونت ایرانین سنز واجبات نیست. و بیشتر جنبه زیبایی داره. هر چند از نظر فنی تو تایپ باعث بهم ریختن تداوم و حرکت چشم و ... هم میشه.
در چندین مقاله خوندم که توصیه کرده بودند به سمتش نریم.
و اگر هم کسی خواست بره حروف متصل به ‍ی رو میشنهاد داده بودند. یک مقدار بد فرم هست پیاده سازیش قالبا شباهت پیدا میکنه به سایر فونت ها.

**Comment by rastikerdar** [comment]
فاصله الف تا ط کم شد.
ممنون بابت گزارش این اشکال
همچنین ممنونم از صالح بابت توضیحات خوبش.
