### ISSUE TITLE
ه چسبان آخر همراه با همزه

### ISSUE THREAD

**Issue by aziz** [rastikerdar/samim-font#40]
چندین نمونه در عکس زیر دیده میشه
<img width="752" alt="screen shot 2015-12-24 at 3 43 13 pm" src="https://cloud.githubusercontent.com/assets/3202/11995690/600d18a2-aa55-11e5-9169-8097b9dc43a7.png">

**Comment by rastikerdar** [comment]
آخ آخ گلیف های هر دو رو اضافه کردم. اما فراموش کرده ام توی تنظیماتشون این آخر بودن رو لحاظ کنم. ببخشید.
آخه توی خود دژاوو هم نبود.

**Comment by rastikerdar** [comment]
در نسخه ۰.۱۰ مرتفع گردید.

ممنونم بابت گزارش خطا
