### ISSUE TITLE
مشکل جدا کننده ارقام

### ISSUE THREAD

**Issue by sIiiS** [rastikerdar/samim-font#42]
در فارسی وقتی ارقام ۳ رقم ۳ رقم از هم جدا میشن، اصولا در پایین اون رقم یه علامتی قرار داده میشه که در فارسی به صورت استاندارد فکر کنم اینه
`‎٬`
حالا این علامت در این فونت در بالای رقم قرار میگیره که فکر کنم بهتره اصلاح بشه
مثال درست : ‎۱۰۵٬۴۴۹

**Comment by rastikerdar** [comment]
توی فونت های میترا و نازنین و تیتر و دژاوو و زر و ... بالا هست. اما توی دروید عربیک و قلم کمپین و ایرانیان سنس و تاهوما پایین هست.

فقط یه مشکلی هست اینه که اگر پایین بزاریمش چه شکلی باشه؟ من توی فونت هایی که پایین هست بررسی کردم شکل ها متفاوت بود.

تاهوما
![screenshot from 2016-02-26 08-29-50](https://cloud.githubusercontent.com/assets/3116038/13343611/7679839c-dc63-11e5-8dc5-12173efa5ddf.png)

قلم آزاد ایرانیان سنس
![screenshot from 2016-02-26 08-30-05](https://cloud.githubusercontent.com/assets/3116038/13343616/84c6f5b0-dc63-11e5-8cbb-fcfa928a82c1.png)

کمپین قلم آزاد
![screenshot from 2016-02-26 08-30-14](https://cloud.githubusercontent.com/assets/3116038/13343619/8cecd886-dc63-11e5-99bd-6f7be0c54d7d.png)

دروید عربیک نسخ
![screenshot from 2016-02-26 08-30-27](https://cloud.githubusercontent.com/assets/3116038/13343626/a6808dec-dc63-11e5-87c3-01cefe61b691.png)

**Comment by sIiiS** [comment]
فکر کنم واسه ما ایرانیا قلم ایرانیان سنس بیشتر شبیه چیزی هست که می نویسیم و رایج تره

**Comment by zoghal** [comment]
جدا کننده هزاره باید در بالا باشه
![momayez_thumb](https://cloud.githubusercontent.com/assets/174688/13408065/fda7702e-df40-11e5-800c-55fdcec4a2a5.png)
![afgdecsep](https://cloud.githubusercontent.com/assets/174688/13408068/0261d6d6-df41-11e5-9a6b-71de44730afc.JPG)
![afg066b](https://cloud.githubusercontent.com/assets/174688/13408079/0b75d498-df41-11e5-95f4-438b70cb8cf4.JPG)

**Comment by rastikerdar** [comment]
صالح جان مشکل اینه که دقیقا فونت هایی داره استفاده میشه که این علامت رو پایین قرار دادند. هر جا هم دیدم پایین بوده. حالا تکلیف چیست؟

راستی صالح جان توی فونت های زیبای نیکا و فربد میخوای این علامت رو کجا قرار بدی؟

**Comment by sIiiS** [comment]
یک مثال ساده میزنم براتون
شما وقتی توی دبستان بهتون هزارگان یاد میدن، وقتی میگن ۳ رقم ۳ رقم جدا کن، اون علامت جداکننده را بالا قرار میدین یا پایین؟
وقتی مثلا یک عدد که میلیونی یا حتی کمتر هست را جایی مینویسید (نه توی کامپیوتر و محیط دیجیتال بلکه به صورت زنده) وقتی ۳ رقمی جدا می کنین،‌جدا کننده را چجوری قرار میدیدن؟
همواره پایین قرار داشته و نمیدونم از کی رفته بالا!
من توی محیط عادی و زنده همچین چیزی ندیدم
فونت هم جدای از محیط عادی نیست و باید قواعد محیط را رعایت کنه

**Comment by msm1365** [comment]
در شرایط نوشتار فارسی روی کاغذ در هر دو حالت از ممیز فارسی استفاده می شود
ممیز فارسی نصف اسلش انگلیسی  است و کمی از خط عدد پایین تر نیز میرود.

**Comment by aziz** [comment]
> جدا کننده هزاره باید در بالا باشه

@zoghal  چرا باید بالا باشه. به طور سنتی و در نسخه‌های دستی بازار و حسابدارهای قدیم این علامت همیشه پایین بوده. 
حالا سوالات من اینه؟ 
- چه کسی تصیمم گرفته این علامت در بالا قرار بگیره؟ آیا این جزئی از استانداردهای صفحه‌کلید فارسی یا جدول یونیکد برای فارسی است. آیا این جزئی از سبک نگارش است که فرهنگستان زبان فارسی در موردش نظر داده؟ مرجعش کجاست؟‌
- سوال دوم اینه که چرا این تصمیم گرفته شده. آیا به دلیل اشتباه شدن این نویسه با ممیز فارسی بوده؟

**Comment by zoghal** [comment]
از تمامی دوستان تقاضا دارم این موضوع رو در این [تاپیک](https://github.com/IranOpenFontGroup/Discussions/issues/5) دنبال و در مباحث مشارکت کنند  تا بتوانیم این مشکل رو به یک نتیجه قابل قبول برسانیم.
#https://github.com/IranOpenFontGroup/Discussions/issues/5

**Comment by sIiiS** [comment]
به نظر من فعلا این مشکل در این فونت حل بشه بعد دنبال موضوع را جای دیگه بگیرید!

**Comment by rastikerdar** [comment]
اعمال شد. با تشکر از گزارش شما.
