### ISSUE TITLE
کمبود بسته کامل فونت

### ISSUE THREAD

**Issue by rastikerdar** [rastikerdar/samim-font#43]
چه به صورت نظر توی وبلاگ و چه پیام های ایمیلی این مورد یعنی کامل نبودن فونت یا مشکل فقدان حروف لاتین گزارش میشه.
از اونجایی که فونت با رویکرد وبی و اپی یا به عبارتی مناسب برای استفاده در ظاهر برنامه ها یا صفحات وب طراحی شد، در طی فرآیند توسعه، اهتمام جدی ای به این مسائل وجود نداشت.

به نظر میاد باید فایل های مختلف برای حالت گوناگون از جمله محیط وب، محیط آفیس، پشتیبانی از حروف لاتین و زبان های ایرانی و یا حالت های دیگری که من اطلاع ندارم تهیه و در بسته فونت گنجانده بشه.

انتخاب فونت انگلیسی مناسب و آزاد برای قرار دادن در فونت نیز خود مرحله مهمیست.
اگر چه ممکن است من هرگز فرصت این کار را پیدا نکنم اما وجود این ایشو می تونه برای آینده این موارد را گوشزد کند.

**Comment by aziz** [comment]
لازمه تاکید کنم که برای وب و برنامه‌های موبایل وجود حروف لاتین مشکل است و نه فقدان آنها

**Comment by sIiiS** [comment]
البته برای وب میشه اول حروف انگلیسی بدون حروف فارسی و سپس حروف فارسی را قرار داد یا برعکس
اما اگر قرار باشه حروفی ادغام بشه، البته نظر من هست، فونت اوپن سانس میتونه کاربردی باشه چون بیشتر سایت‌های خارجی از این فونت استفاده میشه

**Comment by rastikerdar** [comment]
قلم اوپن سنس اضافه شد اما خب حالات مختلف بدون لاتین و ... هم توی بسته قرار گرفت. مصیبت!
هر چی خواستم ازش فرار کردم آخرش گرفتارش شدم!

با تشکر از دوستان.
