### ISSUE TITLE
اضافه کردن فرمت WOFF 2.0

### ISSUE THREAD

**Issue by aziz** [rastikerdar/samim-font#45]
&rlm;نه تنها برای این قلم که برای همه قلم‌ها. 
اگر چه هنوز به دلیل کامل نشده ساپورت این فرمت استفاده‌اش خیلی رایج نیست ولی برای سال آینده باید این کار رو کرد.&lrm;

**Comment by rastikerdar** [comment]
اضافه گردید. ممنونم عزیز جان
