### ISSUE TITLE
بریده‌شدگی بعضی از حروف مثل ص و ی و م و ه

### ISSUE THREAD

**Issue by aziz** [rastikerdar/samim-font#5]
<p>
<img width="188" alt="screen shot 2015-11-14 at 11 56 00 am" src="https://cloud.githubusercontent.com/assets/3202/11163223/890ae66a-8ac7-11e5-80e3-56d6d8106a85.png">
<img width="54" alt="screen shot 2015-11-14 at 11 59 06 am" src="https://cloud.githubusercontent.com/assets/3202/11163228/a51019fc-8ac7-11e5-8539-67ae158938dc.png">
<img width="69" alt="screen shot 2015-11-14 at 12 00 36 pm" src="https://cloud.githubusercontent.com/assets/3202/11163229/a91a625a-8ac7-11e5-9b2d-63ad70260869.png">
<img width="43" alt="screen shot 2015-11-14 at 12 00 44 pm" src="https://cloud.githubusercontent.com/assets/3202/11163230/ab6319bc-8ac7-11e5-9ca6-a12fcb04ac52.png">
</p>

**Comment by rastikerdar** [comment]
این موارد را من در هیچ حالتی در مرورگرها اعم از ویندوز، لینوکس و اندروید ندیدم. اگر بفرمایید در چه شرایطی به این مشکل برخوردید بهتر میشه بررسی نمود.

**Comment by aziz** [comment]
‌Browser: Chrome 46
OS: Mac OS 10.11.2

درسته این مشکل در فایرفاکس و سافاری وجود نداره ولی کماکان کروم این مشکل رو داره

**Comment by aziz** [comment]
<img width="1050" alt="screen shot 2015-11-14 at 3 23 13 pm" src="https://cloud.githubusercontent.com/assets/3202/11163974/afec94ce-8ae3-11e5-82ef-de150ceebde8.png">

**Comment by aziz** [comment]
<img width="1280" alt="screen shot 2015-11-14 at 3 25 14 pm" src="https://cloud.githubusercontent.com/assets/3202/11163982/f2588886-8ae3-11e5-88be-08a1075ebd6c.png">

**Comment by rastikerdar** [comment]
برایم جالبه که به نظر نمایش فونت در تصویر شما بهتر و تمیزتر و شارپ تر است نسبت به آنچه که من در سیستم خودم مشاهده می کنم.

عجیبه کروم توی لینوکس و ویندوز این مشکل را ندارد.
پس توی کروم مک به مشکل بر خوردیم.

**Comment by aziz** [comment]
<p align='right' dir='rtl'>تمیزتر و شارپ‌تر بودن به خاطر اسکرین رتینا مک‌ است. <br>
توصیه میکنم از یک اسکرین های دی پی آی برای طراحی قلم استفاده کنید. 
</p>

**Comment by aziz** [comment]
بریدگی در سایزهای کوچک قابل مشاهده نیست
![screen shot 2015-11-14 at 3 55 58 pm](https://cloud.githubusercontent.com/assets/3202/11164135/52e9debc-8ae8-11e5-8ca6-0467bc63820c.png)

**Comment by artlesshand** [comment]
اینجا میتونید تست کنید blog.sariina.com
هم مطلب زیاده هم همه‌جوره استفاده کردم ازش تقریبا

**Comment by aziz** [comment]
همون آش و همون کاسه.
من این ایشو رو میبندم چون به نظر مشکل از رندرنیگ کروم در مک هستش.
![screen shot 2015-11-14 at 8 19 38 pm](https://cloud.githubusercontent.com/assets/3202/11165379/407ec984-8b0d-11e5-9e20-631e9ed37ac3.png)
<img width="1280" alt="screen shot 2015-11-14 at 8 19 43 pm" src="https://cloud.githubusercontent.com/assets/3202/11165380/438bbcd6-8b0d-11e5-9d02-f89b3e622826.png">

**Comment by artlesshand** [comment]
کدوم ورژن کروم؟

**Comment by rastikerdar** [comment]
سایت شما خیلی زیباست. هم رنگ آمیزی هم نقاشی ها.

**Comment by artlesshand** [comment]
لطف دارید، قلم شمارو که دیدم فوری عوض کردم. کلی قشنگش کرد

**Comment by aziz** [comment]
> ‌ کدوم ورژن کروم؟

Tested in Chrome 46 and 48

**Comment by artlesshand** [comment]
عجیبه من مشکلی ندارم

**Comment by aziz** [comment]
> عجیبه من مشکلی ندارم

OS: Mac OS 10.11.2

تو چی؟

**Comment by artlesshand** [comment]
OS X Yosemite / Chrome 48 Dev

**Comment by aziz** [comment]
پس مشکل از کروم با مک او اس ال کپیتانه

**Comment by artlesshand** [comment]
احتمالا

**Comment by rastikerdar** [comment]
البته فکر می کنم موضوع شارپ بودن به دلیل نوع رندر فونت هست نه اسکرین رتینای مک. چرا که آن چیزی که من در تصویر شما میبینم از دریچه اسکرین مک نیست بلکه سبک رندر هست که البته من حالت رندر خودم رو به آر جی بی تغییر دادم بهتر شد اما باز توی تصویر شما بهتر هست.

البته در مورد اسکرین های دی پی آی که فرمودین من مونیتورم ۹۶ دی پی آی هست و اسکرین موبایل ۱۸۰ دی پی آی. :P
البته خب عادت کردم بزرگنمایی می کنم و اینکه همین دی پی آی پایین هم شاید اسباب خیر شد از اینکه قلم ها  ابتدا برای اندازه ها و رزولوشن های پایین طراحی بشه.

**Comment by aziz** [comment]
هم نوع رندرنیگ و هم رزلوشن بالای عکس (که این به خاطر اسکرینه) اگر کلیک کنی و اندازه اصلی عکس رو ببینی می‌بینی که خیلی بزرگتر از حد معموله. دی پی آی این اسکرین مک ۲۲۷ که تازه در مقایسه با اسمارت فون‌های خوب بازار خیلی پایینه. 
[اینجا رو بیین](http://dpi.lv/)
سامسونگ گلکسی اس ۶ الان ۵۷۷ ه!!!!

من شخصا سعی می‌کنم برای آینده طراحی کنم نه کامپیوتر‌های گذشته.

**Comment by artlesshand** [comment]
دیگه ۳ و ۳.۵ برابر هم داریم فکر کنم

**Comment by behdad222** [comment]
مشکل بریده بودن میتونه از تنظیم نبودن اسندر و دسیندر باشه
سعی میکنم رسیدم خونه یهنگاهی بهش بندازم

**Comment by rastikerdar** [comment]
آخه آقا بهداد ارتفاع این گلیف ها خیلی کمه. به اونجاها فکر نمی کنم برسه.
