### ISSUE TITLE
Load Farsi Digit version from CDN

### ISSUE THREAD

**Issue by ghost** [rastikerdar/samim-font#51]
Is it possible to load Farsi Digit version of this font from CDN?

**Comment by rastikerdar** [comment]
متاسفانه برای سی دی ان تنها نسخه استاندارد قرار داده شده اما خوشبختانه به نظر میاد سایتی به نام فونت‌آپ تمامی نسخه ها رو به صورت سی دی ان قرار داده.
[https://fontup.ir/](https://fontup.ir/)

**Comment by rastikerdar** [comment]
خب تمامی نسخه ها در مخزن قرار گرفت. با تشکر
