### ISSUE TITLE
npm

### ISSUE THREAD

**Issue by sajaddp** [rastikerdar/samim-font#52]
سلام
آقا این فونت رو بر روی npm هم منتشر کردید؟

**Comment by rastikerdar** [comment]
سلام
خیر هنوز. اما انجام خواهد شد.

**Comment by rastikerdar** [comment]
امیدوارم مشکل حل شده باشه با آپدیت جدید. ممنون

**Comment by rastikerdar** [comment]
@theyahya ضمن تشکر اگر امکانش هست مدیریت بسته رو به خود من انتقال بدهید تا بتونم بسته رو برای هر آپدیت مخزن به‌روزرسانی کنم.
نام کاربری من در ان‌پی‌ام:
rastikerdar

**Comment by TheYahya** [comment]
<p dir="rtl">
سلام صابر جان
</p>
<p dir="rtl">
بعنوان maintainer اددت کردم، فک کنم همینجوری باشه، اگه نیاز به چیز دیگه‌ای هست بگو انجام بدم.
</p>

**Comment by VahidN** [comment]
<div dir="rtl">

سلام؛ متاسفانه https://www.npmjs.com/package/samim-font سال‌ها است كه به روز نشده

**Comment by rastikerdar** [comment]
سلام؛ الان به روز شد
