### ISSUE TITLE
Add Kurdish Characters

### ISSUE THREAD

**Issue by mhmd-azeez** [rastikerdar/samim-font#56]
First, I'd have to say that this is very a beautiful and practical font, I love it. Although it's a Farsi font, it only needs a few other characters to be completely usable for [Kurdish](https://en.wikipedia.org/wiki/Central_Kurdish).

These are the missing characters:

- [U+06C6 - ۆ](https://unicode-table.com/en/06C6/)
- [U+06A4 - ڤ](https://unicode-table.com/en/06A4/)
- [U+06B5 - ڵ](https://unicode-table.com/en/06B5/)
- [U+0695 - ڕ](https://unicode-table.com/en/0695/)
- [U+06CE - ێ](https://unicode-table.com/en/06CE/)

I don't have experience in typography, but I'd be happy to help you in whatever way I can. Please let me know if you have any questions.

**Comment by rastikerdar** [comment]
Added to Samim v4.0.0
[rastikerdar.github.io/samim-font/](https://rastikerdar.github.io/samim-font/)

Thanks for this issue

**Comment by mhmd-azeez** [comment]
Well done!
