### ISSUE TITLE
Unexpected strokes on Texts

### ISSUE THREAD

**Issue by ASHKARAN** [rastikerdar/samim-font#57]
We had a new bug report on our native Android client,

Figure 1:
https://i.stack.imgur.com/hQ7ha.png

You can see the application in 3 different devices, everything is fine in figure 1 and 2 But in figure 3 some texts have strokes and look different. we are using this font https://github.com/rastikerdar/samim-font I'll attach two more screenshots from this bug

Figure 2:
https://i.stack.imgur.com/QQTCO.jpg

Figure 3:
https://i.stack.imgur.com/gceq8.jpg

Any idea?

**Comment by rastikerdar** [comment]
Thanks for this issue.
Do you have this problem with other fonts (Yekan, Iran, ... in Note 8) too?

**Comment by rastikerdar** [comment]
Also, please take a look at this link:
https://forums.androidcentral.com/google-nexus-5/467334-why-did-my-font-change-white-black-outline.html
There may be something about adjusting the contrast!

**Comment by ASHKARAN** [comment]
after more research from bug reporter I found out it's his problem all over the phone, and it's not from our app or your font, thanks for the answer
