### ISSUE TITLE
عدم تناسب انحنای نقطه‌های حروف با سایر انحناهای قلم 

### ISSUE THREAD

**Issue by aziz** [rastikerdar/samim-font#6]
<p align='right'>
 به نظرم نقاط باید شکل هندسی‌تری داشته باشند. این قوس‌های تناسبی با ظاهر فونت ندارد. یک مربع با ۴۵ درجه چرخش بهتر است.

<img width="40" alt="screen shot 2015-11-14 at 11 56 26 am" src="https://cloud.githubusercontent.com/assets/3202/11163239/e9699cd6-8ac7-11e5-9de6-3fa3ec64bc85.png">

</p>

**Comment by rastikerdar** [comment]
این یکی از مشکلات چالشی این فونت بود. ابتدا دقیقا به همان صورتی که فرمودید بود که از نسخه 0.9.2 به بعد شکل به حالت فعلی در آمد. مشکل این بود که زاویه های تند در نقطه ها به ویژه در رزولوشن ها یا اندازه های بالا که جزییات مشخص است ظاهر فونت را شلوغ و خشن می کرد تا جایی که احساس می کردم از خوانایی قلم کاسته شده مخصوصا زمانی که تعداد سطور بالا باشد. اما خب شاید هم اشتباه کردم و یک برداشت شخصی یا خطای دید بوده. در ادامه دو تصویر از دو حالت قرار میدم:

![0 9 1](https://cloud.githubusercontent.com/assets/3116038/11163954/24537698-8af8-11e5-80d1-85ae6ddfaca5.png)

![0 9 5](https://cloud.githubusercontent.com/assets/3116038/11163956/41687d00-8af8-11e5-99c0-c2b9485cdd37.png)

نظر شما چیست؟

**Comment by aziz** [comment]
<p align="right">درسته اما شاید کمی کمتر کردن انحناهای نقطه‌ها بهتر باشد. چیزی بین این دو حالت. و یا شاید اولی برای سایزهای کوچک قلم و حالت نرم‌تر برای سایزهای بزرگتر
</p>

**Comment by rastikerdar** [comment]
این حالت بهتر نیست؟
![new dots](https://cloud.githubusercontent.com/assets/3116038/11164711/1f3b4c52-8b0d-11e5-8462-9897597ee0ad.png)

**Comment by aziz** [comment]
<p align='right' dir='rtl'>عالی! 
یه نکته دیگه جاگذاری نقاط دوتایی و سه‌تایی در زیر و بالای حروف است. به نظر در شات بالا نقاط ی کمی باید به سمت چپ کشیده شوند.
</p>

**Comment by rastikerdar** [comment]
بلی، اینو توی ایشوی مربوطه که گذاشتین ادامش میدم :)

**Comment by rastikerdar** [comment]
البته این موضوع آخری که فرمودید من فکر می کردم توی ایشوی دیگه به همین اشاره کرده بودین که اون یه چیز دیگه بود. اگر ممکنه برای این یه ایشوی جدید باز کنید چون این نیاز به یک تغییر ساختاری توی اندازه های تعدادی زیادی از گلیف ها داره.

**Comment by aziz** [comment]
باشه

**Comment by rastikerdar** [comment]
توی شاخه دولوپ 0.9.6 اعمال شد. متشکرم.
