### ISSUE TITLE
نازک شدن الف و لام در نزدیکی بیس‌لاین

### ISSUE THREAD

**Issue by aziz** [rastikerdar/samim-font#7]
<p align='right'>بهتر نیست قطر این حروف یکسان بماند

<p align='right'>
<img width="53" alt="screen shot 2015-11-14 at 11 56 39 am" src="https://cloud.githubusercontent.com/assets/3202/11163260/81f6283e-8ac8-11e5-9cca-e46e5161e51c.png">
<img width="33" alt="screen shot 2015-11-14 at 11 58 16 am" src="https://cloud.githubusercontent.com/assets/3202/11163261/84e54a52-8ac8-11e5-8d85-e3acf8dedb98.png">
<img width="137" alt="screen shot 2015-11-14 at 11 58 30 am" src="https://cloud.githubusercontent.com/assets/3202/11163264/8aea6996-8ac8-11e5-814b-58aa4c8e4b48.png">
<img width="158" alt="screen shot 2015-11-14 at 11 57 52 am" src="https://cloud.githubusercontent.com/assets/3202/11163266/8ce23b66-8ac8-11e5-8b6b-3a734193d3a3.png">

**Comment by rastikerdar** [comment]
به نکته خوبی اشاره فرمودید. در واقع این موضوع ریشه در طراحی فونت دارد. نقطهٔ آغاز طراحی فونت همین شکل الف بود. به عبارتی بر اساس این شکل الف سایر حروف طراحی شدند و اگر شکل دیگری داشت به احتمال زیاد شکل فونت هم کامل تغییر می کرد. در قلم به فراخور نیاز از جمله معیار خوانایی، نرمی و البته نزدیکی به حالت نسخ، ضخامت یا قطر حروف تغییر اندازه داده است. در فونت وزیر به همین شکلی که شما می فرمایید است و تا حدودی ضخامت ها یکسان است. در فونت شبنم که این ویژگی تلاش شده به طور کامل رعایت شود. به هر صورت ممکن است حالتی که شما می فرمایید بهتر باشد. سعی می کنم با این روش شما هم تست کنم.

نکته اینکه به نظر میاد توی همین تصویر واژه "بکلی" حرف ـکـ کمی نیاز به اصلاحات دارد. متشکرم بابت تصویر.

**Comment by aziz** [comment]
<p align='right' dir='rtl'>در الف مجزا خیلی زیباست. بیشتر مشکلم با الف متصل از راست است.

**Comment by rastikerdar** [comment]
الان که دقت می کنم فکر می کنم یک اشنباه طراحی اینجا رخ داده. فکر می کنم در واقع شما با جهت انحنا مشکل دارید که باید از چپ باشد نه راست. یعنی مثل الف باشد. به نظر خودم باید جهتش اینگونه بشه:

![final alef](https://cloud.githubusercontent.com/assets/3116038/11164542/2e33ace4-8b09-11e5-8a4c-d333343f3dcc.png)

اینجوری بهتر نیست؟

**Comment by aziz** [comment]
<p align='right' dir='rtl'>:+1:  خیلی بهتر شد.

**Comment by rastikerdar** [comment]
این نسخه فعلی هست!:
![final alef-before](https://cloud.githubusercontent.com/assets/3116038/11164572/d36321cc-8b09-11e5-93bb-5490422729e2.png)

**Comment by aziz** [comment]
<p align='right' dir='rtl'>آره این قدیمیه کجه شبیه برج پیزا.</p>

**Comment by rastikerdar** [comment]
توی شاخه دولوپ 0.9.6 اعمال شد. متشکرم.

**Comment by artlesshand** [comment]
من با بالاییش موافق‌تر بودم البته

**Comment by rastikerdar** [comment]
![direction0](https://cloud.githubusercontent.com/assets/3116038/11207332/e2e2fbb4-8d29-11e5-9213-0001ffa1fda8.png)

![direction1](https://cloud.githubusercontent.com/assets/3116038/11207331/e29a8640-8d29-11e5-8eb9-986fdc2302a4.png)
به نظرتون پایینی بهتر نیست؟
آخه مشکل این بود که برخی به طرف چپ خم شده بود برخی راست. نتیجه اینکه وقتی با هم ترکیب میشد چپ و راست و بی نظم می شد! 
توی حروف ط ظ ا ـا لـ ـلـ ل و ...

توی دروید عربیک هم نگاه کردم دیدم سعی کرده به یک طرف مایل بشن.

به هر صورت بازش می کنم تا نتیجه قطعی بگیریم.

**Comment by aziz** [comment]
به نظرم که دومی خیلی بهتر و شکیل تر شده. تاثیرش در بلاک‌های متن بلند هم بهتر دیده می‌شه. یه جور نظم دیداری ایجاد می‌کنه

**Comment by artlesshand** [comment]
باید تست شه ولی به نظرم بالایی بهتره.
چون الف و لام متمایزه و شیب اونا فرق داره، در نتیجه اشتباه‌های ناخودآگاه موقع خواندن کم میشه.
حالا باید در متن‌های زیاد امتحانش کنیم.
من نسخه‌ی جدید قلم رو میذارم روی بلاگ سارینا که بتونید تست کنید

**Comment by rastikerdar** [comment]
دست شما درد نکنه

توی وبلاگ شما متوجه شدم کرنینگ ـر ر پشت سر مثلا در واژه «بررسی» هم خراب شده که باید توی فونت اصلاح شه.

**Comment by artlesshand** [comment]
عالی

**Comment by rastikerdar** [comment]
من توی وبلاگ شما بررسی کردم به نظرم خوب میومد. شاید اشتباه می کنم. کیفیت صفحه نمایش من پایینه تفاوتش رو زیاد متوجه نشدم :P

**Comment by artlesshand** [comment]
حالا بعدا بازبینی می‌کنیم اگر آزار دهنده شد. زیاد به یه چیزی دقت کنی عادی میشه
