### ISSUE TITLE
 عدم تناسب زاویه انتهایی سرکش کاف و گاف با سایر زوایای حروف

### ISSUE THREAD

**Issue by aziz** [rastikerdar/samim-font#8]
<p align='right' dir='rtl'>
سایر حروف زاویه بریدگی انتهاییشان غیر عمودی است. این بریدگی عمودی سرکش در کاف و گاف نامتناسب است. 
</p>

<p align='right' dir='rtl'>
<img width="82" alt="screen shot 2015-11-14 at 11 57 19 am" src="https://cloud.githubusercontent.com/assets/3202/11163292/9a12d862-8ac9-11e5-8bc6-0c5e4d0f018a.png">
<img width="158" alt="screen shot 2015-11-14 at 11 57 52 am" src="https://cloud.githubusercontent.com/assets/3202/11163295/9dbc1ffa-8ac9-11e5-96af-b761cd1d559a.png">
<img width="149" alt="screen shot 2015-11-14 at 11 58 40 am" src="https://cloud.githubusercontent.com/assets/3202/11163296/a3652852-8ac9-11e5-8438-4dd5707a8979.png">
</p>

**Comment by rastikerdar** [comment]
روی کاف یه تست زدم. یه جوری میشه. البته حالات دیگه رو هم بررسی می کنم.
فعلی:
![old-kaf](https://cloud.githubusercontent.com/assets/3116038/11164996/de98aa5a-8b16-11e5-9dba-41295b636fd1.png)

جدید:
![new-kaf](https://cloud.githubusercontent.com/assets/3116038/11165000/f5fd0c04-8b16-11e5-8853-1456224473d6.png)

**Comment by aziz** [comment]
به نظرم سرکش حالا می‌تونه کمی بلندتر بشه. 
یا شاید هم تراز عمودی از بین می‌ره اون وقت خیلی سخته فقط تصور کردن.

**Comment by artlesshand** [comment]
یکم شبیه یکان نشد؟

**Comment by rastikerdar** [comment]
به نظرتون اولی منطقی تر نیست؟
توی حالت دوم اگر بخواد بره بالا دیگه خیلی از بقیه حروف بلندتر میشه مگر اینکه فشرده ترش کنیم.

البته ضخامت سرکش هم در قسمت خمیدگی با ابتدای آن یکسان نیست که باید رفع بشه.

**Comment by artlesshand** [comment]
من با اولی موافق‌ترم راستش، چون تناسب بهتری داره با سرکج و بالای الف و لام

**Comment by aziz** [comment]
به نظرتون یه چیزی بین این دو زاویه چطوره؟

**Comment by artlesshand** [comment]
شاید بهتر شه

**Comment by rastikerdar** [comment]
![new2-kaf](https://cloud.githubusercontent.com/assets/3116038/11165258/8596bd4e-8b1f-11e5-85e3-18f7b0728cf0.png)

**Comment by aziz** [comment]
من به این آخری رای می‌دم.
:+1:

**Comment by artlesshand** [comment]
![kaf-gaf-shape](https://cloud.githubusercontent.com/assets/763112/11165307/b77b61a6-8b20-11e5-8a57-4310d8a16196.jpg)

**Comment by artlesshand** [comment]
من با اولی بیشتر ارتباط برقرار می‌کنم

**Comment by behdad222** [comment]
دومی و سومی در سایز ریز خطای دید ایجاد میکنه 
البته فکر کنم

**Comment by rastikerdar** [comment]
به نظر من هم دومی و سومی یه جوری میشه. به نظر میاد یا اصلا نباید زاویه داشته باشه یا با خود بدنه ک هم زاویه بشه

**Comment by aziz** [comment]
پس این ایشو رو همیجا ببنیدیم. نتیجه اینه که بهتره تغییری در این زمینه داده نشه
